### PR TITLE
Tony refactor routing

### PR DESCRIPTION
**Pull request by AnonymousWalker**
Routing.kt is now divided into different controllers in AppModule

```
            homeController()
            languageController(resolver)
            productController(resolver)
            bookController(resolver)
            chapterController(resolver)
```

This change is [Reviewable](https://reviewable.io/reviews/bible-translation-tools/fetcher/62)

### CODE REVIEW

**Review by 16dprice — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/fetcher/62)* status: 0 of 11 files reviewed, 2 unresolved discussions (waiting on @16dprice and @AnonymousWalker)

___
*[src/main/kotlin/org/bibletranslationtools/fetcher/web/controllers/BookController.kt, line 27 at r1](https://reviewable.io/reviews/bible-translation-tools/fetcher/62#-MK4siND6EW7nFg6Lm2p:-MK4siND6EW7nFg6Lm2q:b-a3d4tc) ([raw file](https://github.com/bible-translation-tools/fetcher/blob/1474629067a7f32192d141738352ce97f6890359/src/main/kotlin/org/bibletranslationtools/fetcher/web/controllers/BookController.kt#L27)):*
> ```Kotlin
> 
> fun Routing.bookController(resolver: DependencyResolver) {
>     route("/$GL_ROUTE/{$LANGUAGE_PARAM_KEY}/{$PRODUCT_PARAM_KEY}") {
> ```

why isn't $GL_ROUTE inside curly braces like the other variables here?
___
*[src/main/kotlin/org/bibletranslationtools/fetcher/web/controllers/ChapterController.kt, line 30 at r1](https://reviewable.io/reviews/bible-translation-tools/fetcher/62#-MK4su_r98cIZpyzZQUv:-MK4su_r98cIZpyzZQUw:b-2guby3) ([raw file](https://github.com/bible-translation-tools/fetcher/blob/1474629067a7f32192d141738352ce97f6890359/src/main/kotlin/org/bibletranslationtools/fetcher/web/controllers/ChapterController.kt#L30)):*
> ```Kotlin
> 
> fun Routing.chapterController(resolver: DependencyResolver) {
>     route("/$GL_ROUTE/{$LANGUAGE_PARAM_KEY}/{$PRODUCT_PARAM_KEY}/{$BOOK_PARAM_KEY}") {
> ```

same here

**Comment by AnonymousWalker** [comment]
___
*[src/main/kotlin/org/bibletranslationtools/fetcher/web/controllers/BookController.kt, line 27 at r1](https://reviewable.io/reviews/bible-translation-tools/fetcher/62#-MK4siND6EW7nFg6Lm2p:-MK4tBto1pyzdWSl4_5l:b-4hy5ej) ([raw file](https://github.com/bible-translation-tools/fetcher/blob/1474629067a7f32192d141738352ce97f6890359/src/main/kotlin/org/bibletranslationtools/fetcher/web/controllers/BookController.kt#L27)):*
<details><summary><i>Previously, 16dprice wrote…</i></summary><blockquote>

why isn't $GL_ROUTE inside curly braces like the other variables here?
</blockquote></details>

As it is not a variable parameter. The others {languageCode/bookSlug/...} can vary but "/gl" is fixed

**Comment by AnonymousWalker** [comment]
___
*[src/main/kotlin/org/bibletranslationtools/fetcher/web/controllers/BookController.kt, line 27 at r1](https://reviewable.io/reviews/bible-translation-tools/fetcher/62#-MK4siND6EW7nFg6Lm2p:-MK4tYRO0PEdnDm37eQ3:b-t7mbbo) ([raw file](https://github.com/bible-translation-tools/fetcher/blob/1474629067a7f32192d141738352ce97f6890359/src/main/kotlin/org/bibletranslationtools/fetcher/web/controllers/BookController.kt#L27)):*
<details><summary><i>Previously, AnonymousWalker (Tony) wrote…</i></summary><blockquote>

As it is not a variable parameter. The others {languageCode/bookSlug/...} can vary but "/gl" is fixed
</blockquote></details>

probably later we may have "/hl", then we probably would change that

**Review by jsarabia — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/fetcher/62#-:-MKGZLs9DomCJjxirl0x:bnfp4nl)* status: 0 of 11 files reviewed, all discussions resolved (waiting on @16dprice and @jsarabia)

**Review by jsarabia — APPROVED** [review]

**Pull request merged**
