### PR TITLE
Change language display

### PR DESCRIPTION
**Pull request by AnonymousWalker**
This change is [Reviewable](https://reviewable.io/reviews/bible-translation-tools/fetcher/91)

### CODE REVIEW

**Review by 16dprice — CHANGES_REQUESTED** [review]
> Reviewed 3 of 15 files at r1, 1 of 5 files at r2, 15 of 18 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/fetcher/91)* status: 20 of 21 files reviewed, 3 unresolved discussions (waiting on @16dprice, @AnonymousWalker, and @jsarabia)

___
*[fetcher-web/src/main/kotlin/org/bibletranslationtools/fetcher/repository/LanguageRepository.kt, line 10 at r4](https://reviewable.io/reviews/bible-translation-tools/fetcher/91#-MNxS-cmAH-v8Laf13B6:-MNxS-cn6mdEJeXCaysj:b-1f86gq) ([raw file](https://github.com/bible-translation-tools/fetcher/blob/a00dd583b7b020cb9e8bc683598df774de24632b/fetcher-web/src/main/kotlin/org/bibletranslationtools/fetcher/repository/LanguageRepository.kt#L10)):*
> ```Kotlin
>     fun getHeartLanguages(): List<Language>
>     fun getLanguage(code: String): Language?
>     fun isGateway(code: String): Boolean
> ```

maybe call this isGatewayLanguage? It might make the code elsewhere a bit more readable. This is just a small suggestion though. The way it is here makes sense too. I'm just giving a small thought.
___
*[fetcher-web/src/main/kotlin/org/bibletranslationtools/fetcher/usecase/FetchLanguageViewData.kt, line 42 at r4](https://reviewable.io/reviews/bible-translation-tools/fetcher/91#-MNxUM8kDczQNlE4HvSW:-MNxUM8kDczQNlE4HvSX:b-e3qc7z) ([raw file](https://github.com/bible-translation-tools/fetcher/blob/a00dd583b7b020cb9e8bc683598df774de24632b/fetcher-web/src/main/kotlin/org/bibletranslationtools/fetcher/usecase/FetchLanguageViewData.kt#L42)):*
> ```Kotlin
>     }
> 
>     fun filterLanguages(
> ```

I think this function is doing two things. It's getting the resultLanguages and then it's also performing some logic on line 63 and after to only return certain things. I think there are two levels of abstraction here (the filtering out the languages and then the dropping/taking of a certain amount of languages later).

I think we should replace the val resultsLanguages = ... line with a function call. Maybe getFilteredLanguages(val languageList: List<Language>)???? Or something like that. It should take in the languageRepo.getAll() as it's parameter and then do all of the filtering and return the resultLanguages variable as we have it in this function. That way when I read this function, I only have to understand two things: somehow I'm getting languages that have been filtered down by the query AND that the resultLanguages are being edited a bit in order to return a list of LanguageViewData.

Right now, I have to understand about 6 different things in this function (how the HLs are being filtered, what the var "choices" is, why the fuzzyMatching is at this part of the code, etc.)
___
*[fetcher-web/src/main/kotlin/org/bibletranslationtools/fetcher/web/controllers/utils/ConstantValues.kt, line 3 at r4](https://reviewable.io/reviews/bible-translation-tools/fetcher/91#-MNxTfaG4HsNFYd2crRU:-MNxTfaH6QFSl53ldPls:b-nk1u3g) ([raw file](https://github.com/bible-translation-tools/fetcher/blob/a00dd583b7b020cb9e8bc683598df774de24632b/fetcher-web/src/main/kotlin/org/bibletranslationtools/fetcher/web/controllers/utils/ConstantValues.kt#L3)):*
> ```Kotlin
> package org.bibletranslationtools.fetcher.web.controllers.utils
> 
> const val GL_ROUTE = "gl"
> ```

Should we still be calling this GL_ROUTE? It's not the route for just gateway languages anymore

**Comment by AnonymousWalker** [comment]
___
*[fetcher-web/src/main/kotlin/org/bibletranslationtools/fetcher/web/controllers/utils/ConstantValues.kt, line 3 at r4](https://reviewable.io/reviews/bible-translation-tools/fetcher/91#-MNxTfaG4HsNFYd2crRU:-MNxVmOP3MCxj_NzPUQW:b9unri3) ([raw file](https://github.com/bible-translation-tools/fetcher/blob/a00dd583b7b020cb9e8bc683598df774de24632b/fetcher-web/src/main/kotlin/org/bibletranslationtools/fetcher/web/controllers/utils/ConstantValues.kt#L3)):*
<details><summary><i>Previously, 16dprice wrote…</i></summary><blockquote>

Should we still be calling this GL_ROUTE? It's not the route for just gateway languages anymore
</blockquote></details>

oh because the language view starts with GL anyway, so I think it makes sense to keep it that way.

**Review by 16dprice — DISMISSED** [review]

**Review by jsarabia — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/fetcher/91)* status: 20 of 21 files reviewed, 1 unresolved discussion (waiting on @AnonymousWalker and @jsarabia)

___
*[fetcher-web/src/main/kotlin/org/bibletranslationtools/fetcher/impl/repository/LanguageRepositoryImpl.kt, line 27 at r5](https://reviewable.io/reviews/bible-translation-tools/fetcher/91#-MNxdGvr5DE5txGI1_2Y:-MNxdGvr5DE5txGI1_2Z:bjdrxnb) ([raw file](https://github.com/bible-translation-tools/fetcher/blob/825f5f63d17c548729d01f51d4e8649c16e7404c/fetcher-web/src/main/kotlin/org/bibletranslationtools/fetcher/impl/repository/LanguageRepositoryImpl.kt#L27)):*
> ```Kotlin
>     }
> 
>     override fun isGateway(code: String): Boolean {
> ```

why is this not a boolean field of the Language object? checking if a language is gateway should be O(1) not O(n)

**Review by jsarabia — DISMISSED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/fetcher/91#-:-MNxhjyh4RVmfvyEgAgu:bnfp4nl)* status: 20 of 21 files reviewed, all discussions resolved

**Review by jsarabia — APPROVED** [review]
:lgtm:

> Reviewed 3 of 9 files at r6, 1 of 8 files at r7.
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/fetcher/91#-:-MO2lbxw1PKamn84aeXt:bnfp4nl)* status: 18 of 26 files reviewed, all discussions resolved (waiting on @16dprice and @jsarabia)

**Pull request merged**
