### PR TITLE
Clone and Pull Repos from WACS (daily)

### PR DESCRIPTION
**Pull request by AnonymousWalker**
This change is [Reviewable](https://reviewable.io/reviews/bible-translation-tools/fetcher/79)

### CODE REVIEW

**Review by mXaln — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/fetcher/79)* status: 2 of 3 files reviewed, 6 unresolved discussions (waiting on @AnonymousWalker, @danparisd, @jsarabia, and @mXaln)

___
*[fetcher-pipeline/update_repo.py, line 13 at r1](https://reviewable.io/reviews/bible-translation-tools/fetcher/79#-MMRhLNwDzfPM4ENUMut:-MMRhLNwDzfPM4ENUMuu:b-7z2nzc) ([raw file](https://github.com/bible-translation-tools/fetcher/blob/ebcfc0bbd531cb3328bf48abf7308a8d2adaba56/fetcher-pipeline/update_repo.py#L13)):*
> ```Python
>     def __init__(self):
>         self.repo_dir = os.getenv("ORATURE_REPO_DIR")
>         self.sleep_timer = os.getenv("REFRESH_INTERVAL_HRS") * 3600
> ```

os.getenv always returns String. You need to cast its value to Integer here
___
*[fetcher-pipeline/update_repo.py, line 24 at r1](https://reviewable.io/reviews/bible-translation-tools/fetcher/79#-MMRhaz05hrQegfGzjr7:-MMRhaz14RXbSkpicu_s:b-tg19u2) ([raw file](https://github.com/bible-translation-tools/fetcher/blob/ebcfc0bbd531cb3328bf48abf7308a8d2adaba56/fetcher-pipeline/update_repo.py#L24)):*
> ```Python
>                 if request.status_code == 200:
>                     cmd = GIT_CLONE.format(url)
>                     os.system(cmd)
> ```

I would recommend to use subprocess. Thus we can capture output of the command and log it. Also you can make a process call function in `process_tools.py` script.
Something like:
```
def git_clone(url, verbose=False):
    run_process(
        f'git clone {url}',
        verbose
    )
```

And then you can call that function here
```
git_clone(url, True)
```
___
*[fetcher-pipeline/update_repo.py, line 24 at r1](https://reviewable.io/reviews/bible-translation-tools/fetcher/79#-MMRjIvtEKNgkm9wfR9i:-MMRjIvtEKNgkm9wfR9j:bn7hh8m) ([raw file](https://github.com/bible-translation-tools/fetcher/blob/ebcfc0bbd531cb3328bf48abf7308a8d2adaba56/fetcher-pipeline/update_repo.py#L24)):*
> ```Python
>                 if request.status_code == 200:
>                     cmd = GIT_CLONE.format(url)
>                     os.system(cmd)
> ```

Also when this command will run again, the git command will throw an error "destination path '<repo_name>' already exists and is not an empty directory". So you probably need to clean directories first.
___
*[fetcher-pipeline/update_repo.py, line 27 at r1](https://reviewable.io/reviews/bible-translation-tools/fetcher/79#-MMRiIQgCDu0Oc0auA7-:-MMRiIQgCDu0Oc0auA70:ba761tw) ([raw file](https://github.com/bible-translation-tools/fetcher/blob/ebcfc0bbd531cb3328bf48abf7308a8d2adaba56/fetcher-pipeline/update_repo.py#L27)):*
> ```Python
> 
>         except FileNotFoundError:
>             print("An error occurred when reading file: " + file)
> ```

If an exception is thrown, then your file object might be None, thus it will throw another exception. I recommend to print exception message instead:
```
except FileNotFoundError as e: 
    print("An error occurred when reading file: " + str(e))
```
___
*[fetcher-pipeline/update_repo.py, line 40 at r1](https://reviewable.io/reviews/bible-translation-tools/fetcher/79#-MMRil-F5YH5hPTkMbh6:-MMRil-F5YH5hPTkMbh7:b-enqoh6) ([raw file](https://github.com/bible-translation-tools/fetcher/blob/ebcfc0bbd531cb3328bf48abf7308a8d2adaba56/fetcher-pipeline/update_repo.py#L40)):*
> ```Python
> 
>             # Pull all repos after cloning
>             os.system(PULL_ALL_CMD)
> ```

Same as above, use subprocess
Maybe create a function in `process_tools.py`
```
def pull_all_repos(verbose=False):
    run_process(
        'find . -mindepth 1 -maxdepth 1 -type d -print -exec git -C {} pull \\;',
        verbose
    )
```
And then call it simply 
```
pull_all_repos(True)
```
___
*[fetcher-pipeline/update_repo.py, line 46 at r1](https://reviewable.io/reviews/bible-translation-tools/fetcher/79#-MMRgazZEB-KCVTy9gMV:-MMRgaz_EziKD8OAuNoj:bt3twi7) ([raw file](https://github.com/bible-translation-tools/fetcher/blob/ebcfc0bbd531cb3328bf48abf7308a8d2adaba56/fetcher-pipeline/update_repo.py#L46)):*
> ```Python
> def main():
>     app = RepositoryUpdater()
>     app.start()
> ```

I think your main method will not launch when you run the script. You would need to add __name__ check at the end of the script
```
if __name__ == "__main__":
    main()
```

**Review by mXaln — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/fetcher/79)* status: 2 of 3 files reviewed, 7 unresolved discussions (waiting on @AnonymousWalker, @danparisd, @jsarabia, and @mXaln)

___
*[fetcher-pipeline/update_repo.py, line 32 at r1](https://reviewable.io/reviews/bible-translation-tools/fetcher/79#-MMRjvuk6AzlVqj8AYFu:-MMRjvuk6AzlVqj8AYFv:bptc2aq) ([raw file](https://github.com/bible-translation-tools/fetcher/blob/ebcfc0bbd531cb3328bf48abf7308a8d2adaba56/fetcher-pipeline/update_repo.py#L32)):*
> ```Python
>             file.close()
> 
>     def start(self):
> ```

Add a logger like in "app.py" script

**Review by mXaln — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/fetcher/79)* status: 2 of 3 files reviewed, 7 unresolved discussions (waiting on @AnonymousWalker, @danparisd, @jsarabia, and @mXaln)

___
*[fetcher-pipeline/update_repo.py, line 44 at r1](https://reviewable.io/reviews/bible-translation-tools/fetcher/79#-MMRkFMW8DsU_iaD8NT-:-MMRkFMW8DsU_iaD8NT0:b-cw7ey8) ([raw file](https://github.com/bible-translation-tools/fetcher/blob/ebcfc0bbd531cb3328bf48abf7308a8d2adaba56/fetcher-pipeline/update_repo.py#L44)):*
> ```Python
>             sleep(self.sleep_timer)
> 
> def main():
> ```

Add a logger in the script so we know what happened while script is running
```
logging.basicConfig(format='%(asctime)s - %(levelname)s: %(message)s', level=logging.DEBUG)
```

**Comment by AnonymousWalker** [comment]
___
*[fetcher-pipeline/update_repo.py, line 24 at r1](https://reviewable.io/reviews/bible-translation-tools/fetcher/79#-MMRjIvtEKNgkm9wfR9i:-MMRlswy7YayF6wGvOJS:bopf53o) ([raw file](https://github.com/bible-translation-tools/fetcher/blob/ebcfc0bbd531cb3328bf48abf7308a8d2adaba56/fetcher-pipeline/update_repo.py#L24)):*
<details><summary><i>Previously, mXaln (Maxim) wrote…</i></summary><blockquote>

Also when this command will run again, the git command will throw an error "destination path '<repo_name>' already exists and is not an empty directory". So you probably need to clean directories first.
</blockquote></details>

can we just ignore that? The clone process running everyday, I assume, will only be used for getting the GL that was newly added to WACS.

**Review by AnonymousWalker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/fetcher/79)* status: 1 of 4 files reviewed, 7 unresolved discussions (waiting on @danparisd, @jsarabia, and @mXaln)

___
*[fetcher-pipeline/update_repo.py, line 13 at r1](https://reviewable.io/reviews/bible-translation-tools/fetcher/79#-MMRhLNwDzfPM4ENUMut:-MMS0PcO7Y0LXZAOYbrE:b-jhpxy1) ([raw file](https://github.com/bible-translation-tools/fetcher/blob/ebcfc0bbd531cb3328bf48abf7308a8d2adaba56/fetcher-pipeline/update_repo.py#L13)):*
<details><summary><i>Previously, mXaln (Maxim) wrote…</i></summary><blockquote>

os.getenv always returns String. You need to cast its value to Integer here
</blockquote></details>

I decided to use your approach with an exact time (h:m) instead of an interval
___
*[fetcher-pipeline/update_repo.py, line 24 at r1](https://reviewable.io/reviews/bible-translation-tools/fetcher/79#-MMRhaz05hrQegfGzjr7:-MMS0P297zUADBuXrQ72:b-896fix) ([raw file](https://github.com/bible-translation-tools/fetcher/blob/ebcfc0bbd531cb3328bf48abf7308a8d2adaba56/fetcher-pipeline/update_repo.py#L24)):*
<details><summary><i>Previously, mXaln (Maxim) wrote…</i></summary><blockquote>

I would recommend to use subprocess. Thus we can capture output of the command and log it. Also you can make a process call function in `process_tools.py` script.
Something like:
```
def git_clone(url, verbose=False):
    run_process(
        f'git clone {url}',
        verbose
    )
```

And then you can call that function here
```
git_clone(url, True)
```
</blockquote></details>

Done.
___
*[fetcher-pipeline/update_repo.py, line 27 at r1](https://reviewable.io/reviews/bible-translation-tools/fetcher/79#-MMRiIQgCDu0Oc0auA7-:-MMS0MLb47By8xw5niCx:b-896fix) ([raw file](https://github.com/bible-translation-tools/fetcher/blob/ebcfc0bbd531cb3328bf48abf7308a8d2adaba56/fetcher-pipeline/update_repo.py#L27)):*
<details><summary><i>Previously, mXaln (Maxim) wrote…</i></summary><blockquote>

If an exception is thrown, then your file object might be None, thus it will throw another exception. I recommend to print exception message instead:
```
except FileNotFoundError as e: 
    print("An error occurred when reading file: " + str(e))
```
</blockquote></details>

Done.
___
*[fetcher-pipeline/update_repo.py, line 40 at r1](https://reviewable.io/reviews/bible-translation-tools/fetcher/79#-MMRil-F5YH5hPTkMbh6:-MMS0K5u2cd5mlDBQQXM:b-896fix) ([raw file](https://github.com/bible-translation-tools/fetcher/blob/ebcfc0bbd531cb3328bf48abf7308a8d2adaba56/fetcher-pipeline/update_repo.py#L40)):*
<details><summary><i>Previously, mXaln (Maxim) wrote…</i></summary><blockquote>

Same as above, use subprocess
Maybe create a function in `process_tools.py`
```
def pull_all_repos(verbose=False):
    run_process(
        'find . -mindepth 1 -maxdepth 1 -type d -print -exec git -C {} pull \\;',
        verbose
    )
```
And then call it simply 
```
pull_all_repos(True)
```
</blockquote></details>

Done.
___
*[fetcher-pipeline/update_repo.py, line 44 at r1](https://reviewable.io/reviews/bible-translation-tools/fetcher/79#-MMRkFMW8DsU_iaD8NT-:-MMS0J9B4386_T7uRAgQ:b-896fix) ([raw file](https://github.com/bible-translation-tools/fetcher/blob/ebcfc0bbd531cb3328bf48abf7308a8d2adaba56/fetcher-pipeline/update_repo.py#L44)):*
<details><summary><i>Previously, mXaln (Maxim) wrote…</i></summary><blockquote>

Add a logger in the script so we know what happened while script is running
```
logging.basicConfig(format='%(asctime)s - %(levelname)s: %(message)s', level=logging.DEBUG)
```
</blockquote></details>

Done.
___
*[fetcher-pipeline/update_repo.py, line 46 at r1](https://reviewable.io/reviews/bible-translation-tools/fetcher/79#-MMRgazZEB-KCVTy9gMV:-MMS0Ipf5R4rCl5nFg7P:b-896fix) ([raw file](https://github.com/bible-translation-tools/fetcher/blob/ebcfc0bbd531cb3328bf48abf7308a8d2adaba56/fetcher-pipeline/update_repo.py#L46)):*
<details><summary><i>Previously, mXaln (Maxim) wrote…</i></summary><blockquote>

I think your main method will not launch when you run the script. You would need to add __name__ check at the end of the script
```
if __name__ == "__main__":
    main()
```
</blockquote></details>

Done.

**Review by mXaln — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/fetcher/79)* status: all files reviewed, 1 unresolved discussion (waiting on @AnonymousWalker, @danparisd, and @jsarabia)

___
*[fetcher-pipeline/update_repo.py, line 24 at r1](https://reviewable.io/reviews/bible-translation-tools/fetcher/79#-MMRjIvtEKNgkm9wfR9i:-MMUzawH41zZljIHMt1H:bud0ack) ([raw file](https://github.com/bible-translation-tools/fetcher/blob/ebcfc0bbd531cb3328bf48abf7308a8d2adaba56/fetcher-pipeline/update_repo.py#L24)):*
<details><summary><i>Previously, AnonymousWalker (Tony) wrote…</i></summary><blockquote>

can we just ignore that? The clone process running everyday, I assume, will only be used for getting the GL that was newly added to WACS.
</blockquote></details>

well, first you want to run clone_repos only once when your script starts, so you need to move clone_repos function out of the loop. But if the script fails for some reason, pm2 manager will try to restart it, so there will be a problem of existing repo folders again. That's why you need to delete them before running clone_repos function.

you can make this function:

```
def delete_repo_dirs(self):
    path = Path(self.repo_dir)
    dirs = [f for f in path.iterdir() if f.is_dir()]
    for d in dirs:
        rm_tree(d)
```

and then call it in start method:
```
def start(self):
    self.delete_repo_dirs()
    self.clone_repos()

    while True:
        pull_all_repos(True)
        sleep(self.sleep_timer)
```

**Review by mXaln — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/fetcher/79)* status: all files reviewed, 1 unresolved discussion (waiting on @AnonymousWalker, @danparisd, and @jsarabia)

___
*[fetcher-pipeline/update_repo.py, line 24 at r1](https://reviewable.io/reviews/bible-translation-tools/fetcher/79#-MMRjIvtEKNgkm9wfR9i:-MMV54XG9oCB3HNcTAz4:b-eno1ul) ([raw file](https://github.com/bible-translation-tools/fetcher/blob/ebcfc0bbd531cb3328bf48abf7308a8d2adaba56/fetcher-pipeline/update_repo.py#L24)):*
<details><summary><i>Previously, mXaln (Maxim) wrote…</i></summary><blockquote>

well, first you want to run clone_repos only once when your script starts, so you need to move clone_repos function out of the loop. But if the script fails for some reason, pm2 manager will try to restart it, so there will be a problem of existing repo folders again. That's why you need to delete them before running clone_repos function.

you can make this function:

```
def delete_repo_dirs(self):
    path = Path(self.repo_dir)
    dirs = [f for f in path.iterdir() if f.is_dir()]
    for d in dirs:
        rm_tree(d)
```

and then call it in start method:
```
def start(self):
    self.delete_repo_dirs()
    self.clone_repos()

    while True:
        pull_all_repos(True)
        sleep(self.sleep_timer)
```
</blockquote></details>

P.S. `rm_tree` is the function from `file_utils.py` script

**Review by AnonymousWalker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/fetcher/79)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @danparisd, @jsarabia, and @mXaln)

___
*[fetcher-pipeline/update_repo.py, line 24 at r1](https://reviewable.io/reviews/bible-translation-tools/fetcher/79#-MMRjIvtEKNgkm9wfR9i:-MMVsO3T3TlAYJfvX-IN:be0uq3k) ([raw file](https://github.com/bible-translation-tools/fetcher/blob/ebcfc0bbd531cb3328bf48abf7308a8d2adaba56/fetcher-pipeline/update_repo.py#L24)):*
<details><summary><i>Previously, mXaln (Maxim) wrote…</i></summary><blockquote>

P.S. `rm_tree` is the function from `file_utils.py` script
</blockquote></details>

so I decided to clone only the nonexisting repositories, which will remove the redundant error log

**Review by mXaln — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/fetcher/79)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @AnonymousWalker, @danparisd, @jsarabia, and @mXaln)

___
*[fetcher-pipeline/update_repo.py, line 34 at r4](https://reviewable.io/reviews/bible-translation-tools/fetcher/79#-MMVv9EuDWZf2jS8QlMH:-MMVv9EuDWZf2jS8QlMI:b-qxs37z) ([raw file](https://github.com/bible-translation-tools/fetcher/blob/c03d743a527e5e86aa1fe472095bbbefcd7d214f/fetcher-pipeline/update_repo.py#L34)):*
> ```Python
>             for url in file.read().split():
>                 repo_name = os.path.split(url)[1]
>                 request = requests.head(url)
> ```

I would recommend not to make a request if the repo folder exists.

**Review by AnonymousWalker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/fetcher/79)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @danparisd, @jsarabia, and @mXaln)

___
*[fetcher-pipeline/update_repo.py, line 34 at r4](https://reviewable.io/reviews/bible-translation-tools/fetcher/79#-MMVv9EuDWZf2jS8QlMH:-MMVzMeo3XiTmzuot3v3:b-jyhmk4) ([raw file](https://github.com/bible-translation-tools/fetcher/blob/c03d743a527e5e86aa1fe472095bbbefcd7d214f/fetcher-pipeline/update_repo.py#L34)):*
<details><summary><i>Previously, mXaln (Maxim) wrote…</i></summary><blockquote>

I would recommend not to make a request if the repo folder exists.
</blockquote></details>

okay I made the change

**Review by mXaln — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/fetcher/79)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @AnonymousWalker, @danparisd, @jsarabia, and @mXaln)

___
*[fetcher-pipeline/update_repo.py, line 83 at r5](https://reviewable.io/reviews/bible-translation-tools/fetcher/79#-MMW1DDn6MyHQ3JBDmGA:-MMW1DDn6MyHQ3JBDmGB:b-qyn2h) ([raw file](https://github.com/bible-translation-tools/fetcher/blob/e09e4cc142603bfe2286e713d6a8ba01be0943b3/fetcher-pipeline/update_repo.py#L83)):*
> ```Python
>     logging.basicConfig(format='%(asctime)s - %(levelname)s: %(message)s', level=log_level)
> 
>     hour = args.hour
> ```

You have removed --hour and --minute args from argparser above, so this would not work here. And I would not recommend to add time environments here in python script. Leave it as it was. It would be better to specify them in `entrypoint.sh`, adding prefix of your script. Something like `UPDATE_REPO_EXEC_AT_HOUR` and `UPDATE_REPO_EXEC_AT_MIN`

**Review by mXaln — DISMISSED** [review]
> Reviewed 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/fetcher/79)* status: all files reviewed, 1 unresolved discussion (waiting on @AnonymousWalker, @danparisd, and @jsarabia)

**Review by mXaln — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/fetcher/79)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @danparisd and @jsarabia)

**Review by AnonymousWalker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/fetcher/79)* status: 3 of 5 files reviewed, all discussions resolved (waiting on @danparisd, @jsarabia, and @mXaln)

___
*[fetcher-pipeline/update_repo.py, line 83 at r5](https://reviewable.io/reviews/bible-translation-tools/fetcher/79#-MMW1DDn6MyHQ3JBDmGA:-MMW4-gMBud624s5Du4R:bsztyra) ([raw file](https://github.com/bible-translation-tools/fetcher/blob/e09e4cc142603bfe2286e713d6a8ba01be0943b3/fetcher-pipeline/update_repo.py#L83)):*
<details><summary><i>Previously, mXaln (Maxim) wrote…</i></summary><blockquote>

You have removed --hour and --minute args from argparser above, so this would not work here. And I would not recommend to add time environments here in python script. Leave it as it was. It would be better to specify them in `entrypoint.sh`, adding prefix of your script. Something like `UPDATE_REPO_EXEC_AT_HOUR` and `UPDATE_REPO_EXEC_AT_MIN`
</blockquote></details>

Okay I changed

**Review by mXaln — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/fetcher/79)* status: 3 of 5 files reviewed, all discussions resolved (waiting on @danparisd, @jsarabia, and @mXaln)

**Pull request merged**
