### PR TITLE
Cache content availability

### PR DESCRIPTION
**Pull request by AnonymousWalker**
For chapter and book audio (mp3 & tr), the url is used for determining whether a book or chapter is available or not.

---
This change is [Reviewable](https://reviewable.io/reviews/bible-translation-tools/fetcher/71)

### CODE REVIEW

**Comment by AnonymousWalker** [comment]
### Don't merge this PR in yet as the current dev branch is no longer used

**Review by jsarabia — CHANGES_REQUESTED** [review]
> Reviewed 8 of 29 files at r1, 7 of 26 files at r3, 1 of 5 files at r6.
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/fetcher/71)* status: 16 of 39 files reviewed, 2 unresolved discussions (waiting on @16dprice and @AnonymousWalker)

___
*[src/main/kotlin/org/bibletranslationtools/fetcher/impl/repository/AvailabilityCacheRepo.kt, line 16 at r4](https://reviewable.io/reviews/bible-translation-tools/fetcher/71#-MMGi4LJ87WHZo8lEY1b:-MMGi4LKAwpam-e_L66P:bwbdbx6) ([raw file](https://github.com/bible-translation-tools/fetcher/blob/733a2fc509acb9829212c7652bc9eabca08d7baf/src/main/kotlin/org/bibletranslationtools/fetcher/impl/repository/AvailabilityCacheRepo.kt#L16)):*
> ```Kotlin
>     }
> 
>     @Synchronized
> ```

for this to be valid, you'll need all the methods that access the cache to be annotated with Synchronized as well
___
*[src/main/kotlin/org/bibletranslationtools/fetcher/repository/ContentCacheRepository.kt, line 3 at r4](https://reviewable.io/reviews/bible-translation-tools/fetcher/71#-MMGFZmq2wNIMAPPOPsM:-MMGFZmq2wNIMAPPOPsN:b-hq0vu1) ([raw file](https://github.com/bible-translation-tools/fetcher/blob/733a2fc509acb9829212c7652bc9eabca08d7baf/src/main/kotlin/org/bibletranslationtools/fetcher/repository/ContentCacheRepository.kt#L3)):*
> ```Kotlin
> package org.bibletranslationtools.fetcher.repository
> 
> interface ContentCacheRepository {
> ```

This isn't a "Repository"
Perhaps a better name would be "Accessor"

**Review by AnonymousWalker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/fetcher/71)* status: 15 of 39 files reviewed, 2 unresolved discussions (waiting on @16dprice and @jsarabia)

___
*[src/main/kotlin/org/bibletranslationtools/fetcher/repository/ContentCacheRepository.kt, line 3 at r4](https://reviewable.io/reviews/bible-translation-tools/fetcher/71#-MMGFZmq2wNIMAPPOPsM:-MMGvbGO41UXf7V1m_WT:b-896fix) ([raw file](https://github.com/bible-translation-tools/fetcher/blob/733a2fc509acb9829212c7652bc9eabca08d7baf/src/main/kotlin/org/bibletranslationtools/fetcher/repository/ContentCacheRepository.kt#L3)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

This isn't a "Repository"
Perhaps a better name would be "Accessor"
</blockquote></details>

Done.
___
*[src/main/kotlin/org/bibletranslationtools/fetcher/impl/repository/AvailabilityCacheRepo.kt, line 16 at r4](https://reviewable.io/reviews/bible-translation-tools/fetcher/71#-MMGi4LJ87WHZo8lEY1b:-MMGvVFG0hQ02fypeVCm:b-ikd33s) ([raw file](https://github.com/bible-translation-tools/fetcher/blob/733a2fc509acb9829212c7652bc9eabca08d7baf/src/main/kotlin/org/bibletranslationtools/fetcher/impl/repository/AvailabilityCacheRepo.kt#L16)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

for this to be valid, you'll need all the methods that access the cache to be annotated with Synchronized as well
</blockquote></details>

yep. Better to secure it than not.

**Review by jsarabia — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/fetcher/71#-:-MMHI8bIB1r32vL5qLAt:bnfp4nl)* status: 15 of 39 files reviewed, all discussions resolved (waiting on @16dprice and @jsarabia)

**Pull request merged**
