### PR TITLE
Chapter download for Orature

### PR DESCRIPTION
**Pull request by AnonymousWalker**
All chapters can be requested but may not have the expected content. All languages and all books - Orature file type are available to select.

image

**Request sucessful:**

image

**Request no content:**

image

This change is [Reviewable](https://reviewable.io/reviews/bible-translation-tools/fetcher/67)

### CODE REVIEW

**Comment by AnonymousWalker** [comment]
___
*[src/main/kotlin/org/bibletranslationtools/fetcher/web/controllers/ChapterController.kt, line 65 at r6](https://reviewable.io/reviews/bible-translation-tools/fetcher/67#-MK_1ODG-saHGMRCcNHG:-MK_1ODG-saHGMRCcNHH:bwa6blb) ([raw file](https://github.com/bible-translation-tools/fetcher/blob/8cf3fdb5dd4d913e4446cc18a7d65e5ad3245481/src/main/kotlin/org/bibletranslationtools/fetcher/web/controllers/ChapterController.kt#L65)):*
> ```Kotlin
>                 if (
>                     !validateParameters(params, resolver) ||
>                     params.productSlug != "orature"
> ```

This will be replaced with orature product type

**Review by 16dprice — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/fetcher/67)* status: 0 of 16 files reviewed, 2 unresolved discussions (waiting on @16dprice and @AnonymousWalker)

___
*[src/main/kotlin/org/bibletranslationtools/fetcher/impl/repository/ChapterRepositoryImpl.kt, line 74 at r4](https://reviewable.io/reviews/bible-translation-tools/fetcher/67#-MKZvuNJ2-rTqsioMlnI:-MKZvuNJ2-rTqsioMlnJ:b7neobx) ([raw file](https://github.com/bible-translation-tools/fetcher/blob/fd9db780ada4c6333f6fdc8c61640145efb8abe1/src/main/kotlin/org/bibletranslationtools/fetcher/impl/repository/ChapterRepositoryImpl.kt#L74)):*
> ```Kotlin
>         val url = String.format(rcRepoUrlTemplate, languageCode, resourceId)
>         // download rc from repo
>         val downloadLocation = File("path/on/file/system")
> ```

Is this supposed to be the temp folder? We should set this as an environment variable
___
*[src/main/kotlin/org/bibletranslationtools/fetcher/web/controllers/ChapterController.kt, line 151 at r6](https://reviewable.io/reviews/bible-translation-tools/fetcher/67#-MK_0jfi1nEHdFKo_noz:-MK_0jfi1nEHdFKo_np-:b-g00qkz) ([raw file](https://github.com/bible-translation-tools/fetcher/blob/8cf3fdb5dd4d913e4446cc18a7d65e5ad3245481/src/main/kotlin/org/bibletranslationtools/fetcher/web/controllers/ChapterController.kt#L151)):*
> ```Kotlin
>     resolver: DependencyResolver
> ): String? {
>     if (params.chapter == "all") {
> ```

I think I would prefer that we set this as a constant or something like that. The constant can be "all", but I don't think this particular thing should be hardcoded in the if statement.

**Comment by AnonymousWalker** [comment]
___
*[src/main/kotlin/org/bibletranslationtools/fetcher/web/controllers/ChapterController.kt, line 128 at r6](https://reviewable.io/reviews/bible-translation-tools/fetcher/67#-MK_1_nz9s1QPvCKecjv:-MK_1_o-DYnt_kYZ_O6c:b-4bfaj8) ([raw file](https://github.com/bible-translation-tools/fetcher/blob/8cf3fdb5dd4d913e4446cc18a7d65e5ad3245481/src/main/kotlin/org/bibletranslationtools/fetcher/web/controllers/ChapterController.kt#L128)):*
> ```Kotlin
>         val languageName = getLanguageName(params.languageCode, resolver)
>         val productTitle = getProductTitleKey(params.productSlug, resolver)
>         val isRequestLink = params.productSlug == "orature" // orature file type
> ```

same here, will be replaced with orature product/file type

**Comment by AnonymousWalker** [comment]
___
*[src/main/kotlin/org/bibletranslationtools/fetcher/web/controllers/ChapterController.kt, line 151 at r6](https://reviewable.io/reviews/bible-translation-tools/fetcher/67#-MK_0jfi1nEHdFKo_noz:-MK_1jfs6xHkrgEk62lS:b3xgps2) ([raw file](https://github.com/bible-translation-tools/fetcher/blob/8cf3fdb5dd4d913e4446cc18a7d65e5ad3245481/src/main/kotlin/org/bibletranslationtools/fetcher/web/controllers/ChapterController.kt#L151)):*
<details><summary><i>Previously, 16dprice wrote…</i></summary><blockquote>

I think I would prefer that we set this as a constant or something like that. The constant can be "all", but I don't think this particular thing should be hardcoded in the if statement.
</blockquote></details>

yeah that makes sense

**Comment by AnonymousWalker** [comment]
___
*[src/main/kotlin/org/bibletranslationtools/fetcher/impl/repository/ChapterRepositoryImpl.kt, line 74 at r4](https://reviewable.io/reviews/bible-translation-tools/fetcher/67#-MKZvuNJ2-rTqsioMlnI:-MK_2-LdEzfASIppe6ot:b-ki0a7i) ([raw file](https://github.com/bible-translation-tools/fetcher/blob/fd9db780ada4c6333f6fdc8c61640145efb8abe1/src/main/kotlin/org/bibletranslationtools/fetcher/impl/repository/ChapterRepositoryImpl.kt#L74)):*
<details><summary><i>Previously, 16dprice wrote…</i></summary><blockquote>

Is this supposed to be the temp folder? We should set this as an environment variable
</blockquote></details>

yeah /tmp works

**Review by jsarabia — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/fetcher/67)* status: 0 of 23 files reviewed, 14 unresolved discussions (waiting on @16dprice, @AnonymousWalker, and @jsarabia)

___
*[build.gradle, line 52 at r10](https://reviewable.io/reviews/bible-translation-tools/fetcher/67#-MKkceMUArkti6A_lrbh:-MKkceMV8x_lBwiPljkG:b7x620d) ([raw file](https://github.com/bible-translation-tools/fetcher/blob/352b6db2f0cf4ed1b4485e4783fafb2a98d867ad/build.gradle#L52)):*
> ```Gradle
>     implementation name: "thymeleaf-1.0-SNAPSHOT"
>     implementation "org.wycliffeassociates:kotlin-resource-container:0.6.0"
>     implementation "org.wycliffeassociates:rcmediadownloader:1.1.0"
> ```

please pull the version numbers out into the dependencies file
___
*[src/main/kotlin/org/bibletranslationtools/fetcher/usecase/RequestResourceContainer.kt, line 7 at r10](https://reviewable.io/reviews/bible-translation-tools/fetcher/67#-MKkjHr6426E1-I32580:-MKkjHr6426E1-I32581:b2oxlir) ([raw file](https://github.com/bible-translation-tools/fetcher/blob/352b6db2f0cf4ed1b4485e4783fafb2a98d867ad/src/main/kotlin/org/bibletranslationtools/fetcher/usecase/RequestResourceContainer.kt#L7)):*
> ```Kotlin
> 
> class RequestResourceContainer(private val service: ResourceContainerService) {
>     fun getChapterRC(
> ```

Why not getRC and use polymorphism?
___
*[src/main/kotlin/org/bibletranslationtools/fetcher/web/controllers/utils/UrlParameters.kt, line 3 at r10](https://reviewable.io/reviews/bible-translation-tools/fetcher/67#-MKklQD4AuG8JzGc0LG7:-MKklQD4AuG8JzGc0LG8:b-ufh6eb) ([raw file](https://github.com/bible-translation-tools/fetcher/blob/352b6db2f0cf4ed1b4485e4783fafb2a98d867ad/src/main/kotlin/org/bibletranslationtools/fetcher/web/controllers/utils/UrlParameters.kt#L3)):*
> ```Kotlin
> package org.bibletranslationtools.fetcher.web.controllers.utils
> 
> data class UrlParameters(
> ```

https://stackoverflow.com/a/46376746
___
*[src/main/resources/templates/chapters.html, line 11 at r10](https://reviewable.io/reviews/bible-translation-tools/fetcher/67#-MKkfKkA-rFHNnZDekQ7:-MKkfKkA-rFHNnZDekQ8:b3nix7f) ([raw file](https://github.com/bible-translation-tools/fetcher/blob/352b6db2f0cf4ed1b4485e4783fafb2a98d867ad/src/main/resources/templates/chapters.html#L11)):*
> ```HTML
>     <link rel="stylesheet" href="/static/chapters.css">
>     <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
>     <script th:if="${isRequestLink}" type="text/javascript" src="/static/chapter-request.js"></script>
> ```

can this tag not self close?
___
*[src/main/kotlin/org/bibletranslationtools/fetcher/impl/repository/RCServiceImpl.kt, line 16 at r10](https://reviewable.io/reviews/bible-translation-tools/fetcher/67#-MKkcscL4neGcR0_JkRA:-MKkcscM7YZN7fgYqEqM:b3zu2rk) ([raw file](https://github.com/bible-translation-tools/fetcher/blob/352b6db2f0cf4ed1b4485e4783fafb2a98d867ad/src/main/kotlin/org/bibletranslationtools/fetcher/impl/repository/RCServiceImpl.kt#L16)):*
> ```Kotlin
> class RCServiceImpl : ResourceContainerService {
>     private val rcRepoUrlTemplate = System.getenv("RC_Repository")
>     ?: "https://content.bibletranslationtools.org/WA-Catalog/%s_%s/archive/master.zip"
> ```

could you assign this string to a variable or const?
___
*[src/main/kotlin/org/bibletranslationtools/fetcher/impl/repository/RCServiceImpl.kt, line 25 at r10](https://reviewable.io/reviews/bible-translation-tools/fetcher/67#-MKkdFMK5pmNECP_TFe5:-MKkdFMK5pmNECP_TFe6:b99pzls) ([raw file](https://github.com/bible-translation-tools/fetcher/blob/352b6db2f0cf4ed1b4485e4783fafb2a98d867ad/src/main/kotlin/org/bibletranslationtools/fetcher/impl/repository/RCServiceImpl.kt#L25)):*
> ```Kotlin
>     ): File? {
>         // get the rc from git repo
>         val downloadClient: IDownloadClient = DownloadClient()
> ```

Downloader sounds like a thing that should be provided/injected, not created. Especially not created here in a get function.
___
*[src/main/kotlin/org/bibletranslationtools/fetcher/impl/repository/RCServiceImpl.kt, line 39 at r10](https://reviewable.io/reviews/bible-translation-tools/fetcher/67#-MKkdkr_AvtcRqnwMBmv:-MKkdkr_AvtcRqnwMBmw:blfxqyd) ([raw file](https://github.com/bible-translation-tools/fetcher/blob/352b6db2f0cf4ed1b4485e4783fafb2a98d867ad/src/main/kotlin/org/bibletranslationtools/fetcher/impl/repository/RCServiceImpl.kt#L39)):*
> ```Kotlin
> 
>         // pass into the download library
>         val mediaTypes = listOf(MediaType.WAV, MediaType.MP3)
> ```

this doesn't belong in a method
___
*[src/main/kotlin/org/bibletranslationtools/fetcher/impl/repository/RCServiceImpl.kt, line 52 at r10](https://reviewable.io/reviews/bible-translation-tools/fetcher/67#-MKkdzhtBGGl_Rd4uOwO:-MKkdzhtBGGl_Rd4uOwP:bt2xk56) ([raw file](https://github.com/bible-translation-tools/fetcher/blob/352b6db2f0cf4ed1b4485e4783fafb2a98d867ad/src/main/kotlin/org/bibletranslationtools/fetcher/impl/repository/RCServiceImpl.kt#L52)):*
> ```Kotlin
>             overwrite = true
>         )
>         // verify the chapter is existing
> ```

"existing" should be "exists"
___
*[src/main/kotlin/org/bibletranslationtools/fetcher/impl/repository/RCServiceImpl.kt, line 60 at r10](https://reviewable.io/reviews/bible-translation-tools/fetcher/67#-MKkgNcK7xqnjhX0MaF6:-MKkgNcK7xqnjhX0MaF7:b-kz6euv) ([raw file](https://github.com/bible-translation-tools/fetcher/blob/352b6db2f0cf4ed1b4485e4783fafb2a98d867ad/src/main/kotlin/org/bibletranslationtools/fetcher/impl/repository/RCServiceImpl.kt#L60)):*
> ```Kotlin
>     }
> 
>     override fun getBookRC(
> ```

This method duplicates so much code above; can you refactor to try to reuse commonalities?
___
*[src/main/kotlin/org/bibletranslationtools/fetcher/impl/repository/RCServiceImpl.kt, line 65 at r10](https://reviewable.io/reviews/bible-translation-tools/fetcher/67#-MKkeN5Z72Imsz4MYkFd:-MKkeN5Z72Imsz4MYkFe:bwd9p8q) ([raw file](https://github.com/bible-translation-tools/fetcher/blob/352b6db2f0cf4ed1b4485e4783fafb2a98d867ad/src/main/kotlin/org/bibletranslationtools/fetcher/impl/repository/RCServiceImpl.kt#L65)):*
> ```Kotlin
>         resourceId: String
>     ): File? {
>         val downloadClient: IDownloadClient = DownloadClient()
> ```

as above; this doesn't belong here
___
*[src/main/kotlin/org/bibletranslationtools/fetcher/impl/repository/RCServiceImpl.kt, line 72 at r10](https://reviewable.io/reviews/bible-translation-tools/fetcher/67#-MKkeSlc-ylG0p715b76:-MKkeSlc-ylG0p715b77:b-1ts102) ([raw file](https://github.com/bible-translation-tools/fetcher/blob/352b6db2f0cf4ed1b4485e4783fafb2a98d867ad/src/main/kotlin/org/bibletranslationtools/fetcher/impl/repository/RCServiceImpl.kt#L72)):*
> ```Kotlin
>         ) ?: return null
> 
>         val mediaTypes = listOf(MediaType.WAV, MediaType.MP3)
> ```

doesn't belong here
___
*[src/main/kotlin/org/bibletranslationtools/fetcher/impl/repository/RCServiceImpl.kt, line 105 at r10](https://reviewable.io/reviews/bible-translation-tools/fetcher/67#-MKkg5eHC2gm-jPnkagW:-MKkg5eI4PKksjyHnfHf:bsttrk1) ([raw file](https://github.com/bible-translation-tools/fetcher/blob/352b6db2f0cf4ed1b4485e4783fafb2a98d867ad/src/main/kotlin/org/bibletranslationtools/fetcher/impl/repository/RCServiceImpl.kt#L105)):*
> ```Kotlin
>     }
> 
>     private fun verifyChapterExisting(
> ```

Exists
___
*[src/main/kotlin/org/bibletranslationtools/fetcher/impl/repository/RCServiceImpl.kt, line 136 at r10](https://reviewable.io/reviews/bible-translation-tools/fetcher/67#-MKki_rDBRjEMReYeUkF:-MKki_rDBRjEMReYeUkG:b-9rns66) ([raw file](https://github.com/bible-translation-tools/fetcher/blob/352b6db2f0cf4ed1b4485e4783fafb2a98d867ad/src/main/kotlin/org/bibletranslationtools/fetcher/impl/repository/RCServiceImpl.kt#L136)):*
> ```Kotlin
>     }
> 
>     private fun anyChapterInRC(rcFile: File, slug: String, mediaTypes: List<MediaType>): Boolean {
> ```

This function also shares a ton of similarities to the previous function. Can you try to extract a lot of common code into a function they can both use?
___
*[src/main/kotlin/org/bibletranslationtools/fetcher/repository/ResourceContainerService.kt, line 5 at r10](https://reviewable.io/reviews/bible-translation-tools/fetcher/67#-MKkiq-o8LmLD8ipuBdm:-MKkiq-o8LmLD8ipuBdn:b-wjxnnr) ([raw file](https://github.com/bible-translation-tools/fetcher/blob/352b6db2f0cf4ed1b4485e4783fafb2a98d867ad/src/main/kotlin/org/bibletranslationtools/fetcher/repository/ResourceContainerService.kt#L5)):*
> ```Kotlin
> import java.io.File
> 
> interface ResourceContainerService {
> ```

ResourceContainerServiceForWhatExactly?

**Comment by AnonymousWalker** [comment]
___
*[src/main/resources/templates/chapters.html, line 11 at r10](https://reviewable.io/reviews/bible-translation-tools/fetcher/67#-MKkfKkA-rFHNnZDekQ7:-MKkrrqODeeXmLs_V3f0:b-1qkfgf) ([raw file](https://github.com/bible-translation-tools/fetcher/blob/352b6db2f0cf4ed1b4485e4783fafb2a98d867ad/src/main/resources/templates/chapters.html#L11)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

can this tag not self close?
</blockquote></details>

for <script> tag, it is an exceptional case when even with no content, HTML doesn't understand whether it has or not.
https://www.namasteui.com/why-self-closing-script-tags-doesnt-work/

**Review by AnonymousWalker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/fetcher/67)* status: 0 of 23 files reviewed, 14 unresolved discussions (waiting on @16dprice, @AnonymousWalker, and @jsarabia)

___
*[build.gradle, line 52 at r10](https://reviewable.io/reviews/bible-translation-tools/fetcher/67#-MKkceMUArkti6A_lrbh:-MKo5VqwE6itsL993TjE:b-896fix) ([raw file](https://github.com/bible-translation-tools/fetcher/blob/352b6db2f0cf4ed1b4485e4783fafb2a98d867ad/build.gradle#L52)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

please pull the version numbers out into the dependencies file
</blockquote></details>

Done.
___
*[src/main/kotlin/org/bibletranslationtools/fetcher/usecase/RequestResourceContainer.kt, line 7 at r10](https://reviewable.io/reviews/bible-translation-tools/fetcher/67#-MKkjHr6426E1-I32580:-MKoOlxrDEgd--JwLZQe:b-4e2smk) ([raw file](https://github.com/bible-translation-tools/fetcher/blob/352b6db2f0cf4ed1b4485e4783fafb2a98d867ad/src/main/kotlin/org/bibletranslationtools/fetcher/usecase/RequestResourceContainer.kt#L7)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

Why not getRC and use polymorphism?
</blockquote></details>

Oh it's very similar that I could refactor into just one function, with chapterNumber is nullable
___
*[src/main/kotlin/org/bibletranslationtools/fetcher/impl/repository/RCServiceImpl.kt, line 25 at r10](https://reviewable.io/reviews/bible-translation-tools/fetcher/67#-MKkdFMK5pmNECP_TFe5:-MKoQ0MQ0hxnWyk5fD_S:b-7c11fc) ([raw file](https://github.com/bible-translation-tools/fetcher/blob/352b6db2f0cf4ed1b4485e4783fafb2a98d867ad/src/main/kotlin/org/bibletranslationtools/fetcher/impl/repository/RCServiceImpl.kt#L25)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

Downloader sounds like a thing that should be provided/injected, not created. Especially not created here in a get function.
</blockquote></details>

Done. Injected into rc repository class
___
*[src/main/kotlin/org/bibletranslationtools/fetcher/impl/repository/RCServiceImpl.kt, line 39 at r10](https://reviewable.io/reviews/bible-translation-tools/fetcher/67#-MKkdkr_AvtcRqnwMBmv:-MKoOx7h5d-ep1KAwnDm:b-hqusrf) ([raw file](https://github.com/bible-translation-tools/fetcher/blob/352b6db2f0cf4ed1b4485e4783fafb2a98d867ad/src/main/kotlin/org/bibletranslationtools/fetcher/impl/repository/RCServiceImpl.kt#L39)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

this doesn't belong in a method
</blockquote></details>

Done. I moved it to the use case
___
*[src/main/kotlin/org/bibletranslationtools/fetcher/impl/repository/RCServiceImpl.kt, line 52 at r10](https://reviewable.io/reviews/bible-translation-tools/fetcher/67#-MKkdzhtBGGl_Rd4uOwO:-MKoOw_j-qvJ8CefQvVL:b-896fix) ([raw file](https://github.com/bible-translation-tools/fetcher/blob/352b6db2f0cf4ed1b4485e4783fafb2a98d867ad/src/main/kotlin/org/bibletranslationtools/fetcher/impl/repository/RCServiceImpl.kt#L52)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

"existing" should be "exists"
</blockquote></details>

Done.
___
*[src/main/kotlin/org/bibletranslationtools/fetcher/impl/repository/RCServiceImpl.kt, line 60 at r10](https://reviewable.io/reviews/bible-translation-tools/fetcher/67#-MKkgNcK7xqnjhX0MaF6:-MKoOvpo9B2a0XJi5IZT:b-896fix) ([raw file](https://github.com/bible-translation-tools/fetcher/blob/352b6db2f0cf4ed1b4485e4783fafb2a98d867ad/src/main/kotlin/org/bibletranslationtools/fetcher/impl/repository/RCServiceImpl.kt#L60)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

This method duplicates so much code above; can you refactor to try to reuse commonalities?
</blockquote></details>

Done.
___
*[src/main/kotlin/org/bibletranslationtools/fetcher/impl/repository/RCServiceImpl.kt, line 65 at r10](https://reviewable.io/reviews/bible-translation-tools/fetcher/67#-MKkeN5Z72Imsz4MYkFd:-MKoOiAbAzrPQZmIGGiF:b-896fix) ([raw file](https://github.com/bible-translation-tools/fetcher/blob/352b6db2f0cf4ed1b4485e4783fafb2a98d867ad/src/main/kotlin/org/bibletranslationtools/fetcher/impl/repository/RCServiceImpl.kt#L65)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

as above; this doesn't belong here
</blockquote></details>

Done.
___
*[src/main/kotlin/org/bibletranslationtools/fetcher/impl/repository/RCServiceImpl.kt, line 72 at r10](https://reviewable.io/reviews/bible-translation-tools/fetcher/67#-MKkeSlc-ylG0p715b76:-MKoOhV05xOrfqpzNFWH:b-896fix) ([raw file](https://github.com/bible-translation-tools/fetcher/blob/352b6db2f0cf4ed1b4485e4783fafb2a98d867ad/src/main/kotlin/org/bibletranslationtools/fetcher/impl/repository/RCServiceImpl.kt#L72)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

doesn't belong here
</blockquote></details>

Done.
___
*[src/main/kotlin/org/bibletranslationtools/fetcher/impl/repository/RCServiceImpl.kt, line 105 at r10](https://reviewable.io/reviews/bible-translation-tools/fetcher/67#-MKkg5eHC2gm-jPnkagW:-MKoOjua7dwTxgYjYnDy:b-896fix) ([raw file](https://github.com/bible-translation-tools/fetcher/blob/352b6db2f0cf4ed1b4485e4783fafb2a98d867ad/src/main/kotlin/org/bibletranslationtools/fetcher/impl/repository/RCServiceImpl.kt#L105)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

Exists
</blockquote></details>

Done.
___
*[src/main/kotlin/org/bibletranslationtools/fetcher/impl/repository/RCServiceImpl.kt, line 136 at r10](https://reviewable.io/reviews/bible-translation-tools/fetcher/67#-MKki_rDBRjEMReYeUkF:-MKoOkxN7cF899vCV1sC:b-896fix) ([raw file](https://github.com/bible-translation-tools/fetcher/blob/352b6db2f0cf4ed1b4485e4783fafb2a98d867ad/src/main/kotlin/org/bibletranslationtools/fetcher/impl/repository/RCServiceImpl.kt#L136)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

This function also shares a ton of similarities to the previous function. Can you try to extract a lot of common code into a function they can both use?
</blockquote></details>

Done.
___
*[src/main/kotlin/org/bibletranslationtools/fetcher/repository/ResourceContainerService.kt, line 5 at r10](https://reviewable.io/reviews/bible-translation-tools/fetcher/67#-MKkiq-o8LmLD8ipuBdm:-MKoOb6p0gru6yqDcAcN:bjpjbdx) ([raw file](https://github.com/bible-translation-tools/fetcher/blob/352b6db2f0cf4ed1b4485e4783fafb2a98d867ad/src/main/kotlin/org/bibletranslationtools/fetcher/repository/ResourceContainerService.kt#L5)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

ResourceContainerServiceForWhatExactly?
</blockquote></details>

So I think ResourceContainerRepository sounds better

**Review by jsarabia — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/fetcher/67)* status: 0 of 23 files reviewed, 4 unresolved discussions (waiting on @16dprice, @AnonymousWalker, and @jsarabia)

___
*[src/main/kotlin/org/bibletranslationtools/fetcher/impl/repository/RCRepositoryImpl.kt, line 38 at r11](https://reviewable.io/reviews/bible-translation-tools/fetcher/67#-MKoRjSMEVkcHax1Lqw_:-MKoRjSMEVkcHax1Lqwa:bm8qlzg) ([raw file](https://github.com/bible-translation-tools/fetcher/blob/0c343a7bd7c8b9f1c63abb60ce1a0be3ef25c28b/src/main/kotlin/org/bibletranslationtools/fetcher/impl/repository/RCRepositoryImpl.kt#L38)):*
> ```Kotlin
>             "${languageCode}_${resourceId}_${bookSlug}.${templateRC.extension}" // book rc
>         } else {
>             "${languageCode}_${resourceId}_${bookSlug}_c${chapterNumber}.${templateRC.extension}" // chapter rc
> ```

make this a function
___
*[src/main/kotlin/org/bibletranslationtools/fetcher/usecase/RequestResourceContainer.kt, line 7 at r10](https://reviewable.io/reviews/bible-translation-tools/fetcher/67#-MKkjHr6426E1-I32580:-MKoR12D2u-A-8Q-C8-E:bz87j7g) ([raw file](https://github.com/bible-translation-tools/fetcher/blob/352b6db2f0cf4ed1b4485e4783fafb2a98d867ad/src/main/kotlin/org/bibletranslationtools/fetcher/usecase/RequestResourceContainer.kt#L7)):*
<details><summary><i>Previously, AnonymousWalker (Tony) wrote…</i></summary><blockquote>

Oh it's very similar that I could refactor into just one function, with chapterNumber is nullable
</blockquote></details>

Please do

**Comment by AnonymousWalker** [comment]
___
*[src/main/kotlin/org/bibletranslationtools/fetcher/impl/repository/RCServiceImpl.kt, line 16 at r10](https://reviewable.io/reviews/bible-translation-tools/fetcher/67#-MKkcscL4neGcR0_JkRA:-MKoTnCBAY2Yv9KmoJlL:b-6v0d50) ([raw file](https://github.com/bible-translation-tools/fetcher/blob/352b6db2f0cf4ed1b4485e4783fafb2a98d867ad/src/main/kotlin/org/bibletranslationtools/fetcher/impl/repository/RCServiceImpl.kt#L16)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

could you assign this string to a variable or const?
</blockquote></details>

Which string is it? The url or the env var?

**Review by AnonymousWalker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/fetcher/67)* status: 0 of 23 files reviewed, 4 unresolved discussions (waiting on @16dprice, @AnonymousWalker, and @jsarabia)

___
*[src/main/kotlin/org/bibletranslationtools/fetcher/impl/repository/RCRepositoryImpl.kt, line 38 at r11](https://reviewable.io/reviews/bible-translation-tools/fetcher/67#-MKoRjSMEVkcHax1Lqw_:-MKoTmZC0fGnYAs0shq_:b-896fix) ([raw file](https://github.com/bible-translation-tools/fetcher/blob/0c343a7bd7c8b9f1c63abb60ce1a0be3ef25c28b/src/main/kotlin/org/bibletranslationtools/fetcher/impl/repository/RCRepositoryImpl.kt#L38)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

make this a function
</blockquote></details>

Done.
___
*[src/main/kotlin/org/bibletranslationtools/fetcher/usecase/RequestResourceContainer.kt, line 7 at r10](https://reviewable.io/reviews/bible-translation-tools/fetcher/67#-MKkjHr6426E1-I32580:-MKoVbzV7AST5791LPrA:b-896fix) ([raw file](https://github.com/bible-translation-tools/fetcher/blob/352b6db2f0cf4ed1b4485e4783fafb2a98d867ad/src/main/kotlin/org/bibletranslationtools/fetcher/usecase/RequestResourceContainer.kt#L7)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

Please do
</blockquote></details>

Done.

**Review by AnonymousWalker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/fetcher/67)* status: 0 of 25 files reviewed, 4 unresolved discussions (waiting on @16dprice and @jsarabia)

___
*[src/main/kotlin/org/bibletranslationtools/fetcher/web/controllers/utils/UrlParameters.kt, line 3 at r10](https://reviewable.io/reviews/bible-translation-tools/fetcher/67#-MKklQD4AuG8JzGc0LG7:-MKpKTGJCpOroQBWOout:b6fv79q) ([raw file](https://github.com/bible-translation-tools/fetcher/blob/352b6db2f0cf4ed1b4485e4783fafb2a98d867ad/src/main/kotlin/org/bibletranslationtools/fetcher/web/controllers/utils/UrlParameters.kt#L3)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

https://stackoverflow.com/a/46376746
</blockquote></details>

I used the overridden get() method. The constructor parameter names are changed, too

**Review by jsarabia — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/fetcher/67)* status: 0 of 25 files reviewed, 3 unresolved discussions (waiting on @16dprice, @AnonymousWalker, and @jsarabia)

___
*[src/main/kotlin/org/bibletranslationtools/fetcher/impl/repository/RCRepositoryImpl.kt, line 24 at r13](https://reviewable.io/reviews/bible-translation-tools/fetcher/67#-MKpNYUO3gGOMOfUB0Yg:-MKpNYUO3gGOMOfUB0Yh:b-owsk2a) ([raw file](https://github.com/bible-translation-tools/fetcher/blob/564e7d4e48d4e79ad322360b3e9346c160949d46/src/main/kotlin/org/bibletranslationtools/fetcher/impl/repository/RCRepositoryImpl.kt#L24)):*
> ```Kotlin
>         mediaTypes: List<MediaType>,
>         chapterNumber: Int?,
>         resourceId: String
> ```

everything here uses a ton of parameters. Why pass around primitives? This seems like an unnamed object that you could pass to everything. In fact, these arguments are really similar to the UrlParameters object
___
*[src/main/kotlin/org/bibletranslationtools/fetcher/web/controllers/utils/UrlParameters.kt, line 3 at r10](https://reviewable.io/reviews/bible-translation-tools/fetcher/67#-MKklQD4AuG8JzGc0LG7:-MKpNGmb28YD1bp2TExu:b-mw6iu3) ([raw file](https://github.com/bible-translation-tools/fetcher/blob/352b6db2f0cf4ed1b4485e4783fafb2a98d867ad/src/main/kotlin/org/bibletranslationtools/fetcher/web/controllers/utils/UrlParameters.kt#L3)):*
<details><summary><i>Previously, AnonymousWalker (Tony) wrote…</i></summary><blockquote>

I used the overridden get() method. The constructor parameter names are changed, too
</blockquote></details>

switch to Class, remove private val from the constructor args, and use the same variable names as per the stackoverflow article

**Review by AnonymousWalker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/fetcher/67)* status: 0 of 25 files reviewed, 3 unresolved discussions (waiting on @16dprice, @AnonymousWalker, and @jsarabia)

___
*[src/main/kotlin/org/bibletranslationtools/fetcher/web/controllers/utils/UrlParameters.kt, line 3 at r10](https://reviewable.io/reviews/bible-translation-tools/fetcher/67#-MKklQD4AuG8JzGc0LG7:-MKpSfOqAkmEZTd80IG-:b-896fix) ([raw file](https://github.com/bible-translation-tools/fetcher/blob/352b6db2f0cf4ed1b4485e4783fafb2a98d867ad/src/main/kotlin/org/bibletranslationtools/fetcher/web/controllers/utils/UrlParameters.kt#L3)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

switch to Class, remove private val from the constructor args, and use the same variable names as per the stackoverflow article
</blockquote></details>

Done.

**Review by AnonymousWalker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/fetcher/67)* status: 0 of 25 files reviewed, 1 unresolved discussion (waiting on @16dprice and @jsarabia)

___
*[src/main/kotlin/org/bibletranslationtools/fetcher/impl/repository/RCRepositoryImpl.kt, line 24 at r13](https://reviewable.io/reviews/bible-translation-tools/fetcher/67#-MKpNYUO3gGOMOfUB0Yg:-MKphrcK-AH6b-Kx3NdY:bp8qmb) ([raw file](https://github.com/bible-translation-tools/fetcher/blob/564e7d4e48d4e79ad322360b3e9346c160949d46/src/main/kotlin/org/bibletranslationtools/fetcher/impl/repository/RCRepositoryImpl.kt#L24)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

everything here uses a ton of parameters. Why pass around primitives? This seems like an unnamed object that you could pass to everything. In fact, these arguments are really similar to the UrlParameters object
</blockquote></details>

I try with UrlParameters as the argument object, which makes the code much shorter

**Review by jsarabia — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/fetcher/67#-:-MLEoUsY81E7XiYzvmbZ:bnfp4nl)* status: 0 of 37 files reviewed, 1 unresolved discussion (waiting on @16dprice and @jsarabia)

**Pull request merged**
