### PR TITLE
Find source text repos in port and clone them

### PR DESCRIPTION
**Pull request by mXaln**
This change is [Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Fetcher/198)

### CODE REVIEW

**Review by AnonymousWalker — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Fetcher/198)* status: 0 of 21 files reviewed, 3 unresolved discussions (waiting on @mXaln)

___
*[`fetcher-web/src/main/kotlin/org/bibletranslationtools/fetcher/impl/repository/PrimaryRepoRepositoryImpl.kt` line 8 at r2](https://reviewable.io/reviews/Bible-Translation-Tools/Fetcher/198#-Ny76RYX4w2CRY4dauq7:-Ny76RYX4w2CRY4dauq8:b-8ty57s) ([raw file](https://github.com/Bible-Translation-Tools/Fetcher/blob/6b042d0420b4133a92d471c2fb0744cd5f48850b/fetcher-web/src/main/kotlin/org/bibletranslationtools/fetcher/impl/repository/PrimaryRepoRepositoryImpl.kt#L8)):*
> ```Kotlin
> import org.bibletranslationtools.fetcher.repository.PrimaryRepoRepository
> 
> class PrimaryRepoRepositoryImpl : PrimaryRepoRepository {
> ```

To avoid confusion with repeating the same word, could we rename to `PrimaryRepoAccessor` or `ContentRepoAccessor`?
___
*[`fetcher-web/src/main/kotlin/org/bibletranslationtools/fetcher/impl/repository/StorageAccessImpl.kt` line 69 at r2](https://reviewable.io/reviews/Bible-Translation-Tools/Fetcher/198#-Ny77GqP5JC5AAhvE-IX:-Ny77GqP5JC5AAhvE-IY:bo43rdc) ([raw file](https://github.com/Bible-Translation-Tools/Fetcher/blob/6b042d0420b4133a92d471c2fb0744cd5f48850b/fetcher-web/src/main/kotlin/org/bibletranslationtools/fetcher/impl/repository/StorageAccessImpl.kt#L69)):*
> ```Kotlin
>     }
> 
>     override fun getReposRoot(): File {
> ```

could we name it `getReposDir()`?
___
*[`fetcher-web/src/main/kotlin/org/bibletranslationtools/fetcher/usecase/CloneRemoteRepo.kt` line 11 at r2](https://reviewable.io/reviews/Bible-Translation-Tools/Fetcher/198#-Ny77cEHA6xvb6j95Hr2:-Ny77cEHA6xvb6j95Hr3:bfl2c8s) ([raw file](https://github.com/Bible-Translation-Tools/Fetcher/blob/6b042d0420b4133a92d471c2fb0744cd5f48850b/fetcher-web/src/main/kotlin/org/bibletranslationtools/fetcher/usecase/CloneRemoteRepo.kt#L11)):*
> ```Kotlin
>     private val logger = LoggerFactory.getLogger(javaClass)
> 
>     fun cloneRepo(
> ```

we could move this to the PrimaryRepo__ API, since we already have `getRepoUrl()` in there.  `downloadRepo()` would be preferred

**Review by mXaln — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Fetcher/198)* status: 0 of 25 files reviewed, 3 unresolved discussions (waiting on @AnonymousWalker)

___
*[`fetcher-web/src/main/kotlin/org/bibletranslationtools/fetcher/impl/repository/StorageAccessImpl.kt` line 69 at r2](https://reviewable.io/reviews/Bible-Translation-Tools/Fetcher/198#-Ny77GqP5JC5AAhvE-IX:-NyKC3KVEVlqYLcOQdrU:b-896fix) ([raw file](https://github.com/Bible-Translation-Tools/Fetcher/blob/6b042d0420b4133a92d471c2fb0744cd5f48850b/fetcher-web/src/main/kotlin/org/bibletranslationtools/fetcher/impl/repository/StorageAccessImpl.kt#L69)):*
<details><summary><i>Previously, AnonymousWalker (Tony) wrote…</i></summary><blockquote>

could we name it `getReposDir()`?
</blockquote></details>

Done.
___
*[`fetcher-web/src/main/kotlin/org/bibletranslationtools/fetcher/usecase/CloneRemoteRepo.kt` line 11 at r2](https://reviewable.io/reviews/Bible-Translation-Tools/Fetcher/198#-Ny77cEHA6xvb6j95Hr2:-NyKC0Me1iOIw4zr1i5N:b3z5u80) ([raw file](https://github.com/Bible-Translation-Tools/Fetcher/blob/6b042d0420b4133a92d471c2fb0744cd5f48850b/fetcher-web/src/main/kotlin/org/bibletranslationtools/fetcher/usecase/CloneRemoteRepo.kt#L11)):*
<details><summary><i>Previously, AnonymousWalker (Tony) wrote…</i></summary><blockquote>

we could move this to the PrimaryRepo__ API, since we already have `getRepoUrl()` in there.  `downloadRepo()` would be preferred
</blockquote></details>

Done. By refactoring to use SourceCacheAccessor
___
*[`fetcher-web/src/main/kotlin/org/bibletranslationtools/fetcher/impl/repository/PrimaryRepoRepositoryImpl.kt` line 8 at r2](https://reviewable.io/reviews/Bible-Translation-Tools/Fetcher/198#-Ny76RYX4w2CRY4dauq7:-NyKC7FQ6wDM7KgqEpqt:bjoo18j) ([raw file](https://github.com/Bible-Translation-Tools/Fetcher/blob/6b042d0420b4133a92d471c2fb0744cd5f48850b/fetcher-web/src/main/kotlin/org/bibletranslationtools/fetcher/impl/repository/PrimaryRepoRepositoryImpl.kt#L8)):*
<details><summary><i>Previously, AnonymousWalker (Tony) wrote…</i></summary><blockquote>

To avoid confusion with repeating the same word, could we rename to `PrimaryRepoAccessor` or `ContentRepoAccessor`?
</blockquote></details>

Done. I have removed PrimaryRepoAccessor. Instead I came up to using your idea of cache accessor, that will fetch available repos for all languages in PORT on server start (takes up to 10 seconds). Then I'm going to use this cache to get availability status of the source texts for any language.

**Review by AnonymousWalker — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Fetcher/198)* status: 0 of 25 files reviewed, 6 unresolved discussions (waiting on @mXaln)

___
*[`fetcher-web/src/main/kotlin/org/bibletranslationtools/fetcher/impl/repository/SourceAvailabilityCacheAccessor.kt` line 8 at r4](https://reviewable.io/reviews/Bible-Translation-Tools/Fetcher/198#-NyLI2g49iW7Lz8zPjZr:-NyLI2g49iW7Lz8zPjZs:b-s8dqiz) ([raw file](https://github.com/Bible-Translation-Tools/Fetcher/blob/2ffce805b99010774a3de43495a52a1ee3c70903/fetcher-web/src/main/kotlin/org/bibletranslationtools/fetcher/impl/repository/SourceAvailabilityCacheAccessor.kt#L8)):*
> ```Kotlin
> import org.slf4j.LoggerFactory
> 
> class SourceAvailabilityCacheAccessor(
> ```

`SourceTextAccessor `
or
`SourceTextRepository`
___
*[`fetcher-web/src/main/kotlin/org/bibletranslationtools/fetcher/impl/repository/SourceAvailabilityCacheAccessor.kt` line 30 at r4](https://reviewable.io/reviews/Bible-Translation-Tools/Fetcher/198#-NyLBB7OEgGzLKOmrzHJ:-NyLBB7OEgGzLKOmrzHK:bfx0os9) ([raw file](https://github.com/Bible-Translation-Tools/Fetcher/blob/2ffce805b99010774a3de43495a52a1ee3c70903/fetcher-web/src/main/kotlin/org/bibletranslationtools/fetcher/impl/repository/SourceAvailabilityCacheAccessor.kt#L30)):*
> ```Kotlin
>     }
> 
>     override fun downloadRepo(repoName: String, repoUrl: String) {
> ```

this function doesn't seem to have any relationship with this class. You could consider moving it to the RC repo
___
*[`fetcher-web/src/main/kotlin/org/bibletranslationtools/fetcher/impl/repository/SourceAvailabilityCacheAccessor.kt` line 34 at r4](https://reviewable.io/reviews/Bible-Translation-Tools/Fetcher/198#-NyL6sv5Byk3QlERV_kY:-NyL6sv5Byk3QlERV_kZ:b-1icc8y) ([raw file](https://github.com/Bible-Translation-Tools/Fetcher/blob/2ffce805b99010774a3de43495a52a1ee3c70903/fetcher-web/src/main/kotlin/org/bibletranslationtools/fetcher/impl/repository/SourceAvailabilityCacheAccessor.kt#L34)):*
> ```Kotlin
> 
>         val process = ProcessBuilder()
>             .command("git", "clone", repoUrl, repoName)
> ```

Fetcher web server doesn't seem to be a good place for using external process. The pipeline script using `git clone` is located outside of Fetcher webapp.

How do you think if we use HTTP request to download the repo instead?
___
*[`fetcher-web/src/main/kotlin/org/bibletranslationtools/fetcher/impl/repository/PrimaryRepoRepositoryImpl.kt` line 8 at r2](https://reviewable.io/reviews/Bible-Translation-Tools/Fetcher/198#-Ny76RYX4w2CRY4dauq7:-NyL8546DQAU_u_FPGA3:b-hhaoum) ([raw file](https://github.com/Bible-Translation-Tools/Fetcher/blob/6b042d0420b4133a92d471c2fb0744cd5f48850b/fetcher-web/src/main/kotlin/org/bibletranslationtools/fetcher/impl/repository/PrimaryRepoRepositoryImpl.kt#L8)):*
<details><summary><i>Previously, mXaln (Maxim) wrote…</i></summary><blockquote>

Done. I have removed PrimaryRepoAccessor. Instead I came up to using your idea of cache accessor, that will fetch available repos for all languages in PORT on server start (takes up to 10 seconds). Then I'm going to use this cache to get availability status of the source texts for any language.
</blockquote></details>

I agree on the idea. For your case, given this class with 1 method, you could just put this in your cache accessor. It's not necessary to have a dedicated builder that has a single method.

**Review by mXaln — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Fetcher/198)* status: 0 of 26 files reviewed, 6 unresolved discussions (waiting on @AnonymousWalker)

___
*[`fetcher-web/src/main/kotlin/org/bibletranslationtools/fetcher/impl/repository/SourceAvailabilityCacheAccessor.kt` line 8 at r4](https://reviewable.io/reviews/Bible-Translation-Tools/Fetcher/198#-NyLI2g49iW7Lz8zPjZr:-NyLUsRnCSbGegCuXyoO:b-896fix) ([raw file](https://github.com/Bible-Translation-Tools/Fetcher/blob/2ffce805b99010774a3de43495a52a1ee3c70903/fetcher-web/src/main/kotlin/org/bibletranslationtools/fetcher/impl/repository/SourceAvailabilityCacheAccessor.kt#L8)):*
<details><summary><i>Previously, AnonymousWalker (Tony) wrote…</i></summary><blockquote>

`SourceTextAccessor `
or
`SourceTextRepository`
</blockquote></details>

Done.
___
*[`fetcher-web/src/main/kotlin/org/bibletranslationtools/fetcher/impl/repository/SourceAvailabilityCacheAccessor.kt` line 30 at r4](https://reviewable.io/reviews/Bible-Translation-Tools/Fetcher/198#-NyLBB7OEgGzLKOmrzHJ:-NyLUv1x3M4qQB9u5C5J:b-896fix) ([raw file](https://github.com/Bible-Translation-Tools/Fetcher/blob/2ffce805b99010774a3de43495a52a1ee3c70903/fetcher-web/src/main/kotlin/org/bibletranslationtools/fetcher/impl/repository/SourceAvailabilityCacheAccessor.kt#L30)):*
<details><summary><i>Previously, AnonymousWalker (Tony) wrote…</i></summary><blockquote>

this function doesn't seem to have any relationship with this class. You could consider moving it to the RC repo
</blockquote></details>

Done.
___
*[`fetcher-web/src/main/kotlin/org/bibletranslationtools/fetcher/impl/repository/SourceAvailabilityCacheAccessor.kt` line 34 at r4](https://reviewable.io/reviews/Bible-Translation-Tools/Fetcher/198#-NyL6sv5Byk3QlERV_kY:-NyLUykgCLaype5qS38M:b-jdvpio) ([raw file](https://github.com/Bible-Translation-Tools/Fetcher/blob/2ffce805b99010774a3de43495a52a1ee3c70903/fetcher-web/src/main/kotlin/org/bibletranslationtools/fetcher/impl/repository/SourceAvailabilityCacheAccessor.kt#L34)):*
<details><summary><i>Previously, AnonymousWalker (Tony) wrote…</i></summary><blockquote>

Fetcher web server doesn't seem to be a good place for using external process. The pipeline script using `git clone` is located outside of Fetcher webapp.

How do you think if we use HTTP request to download the repo instead?
</blockquote></details>

I don't think that a web server can't use native git client. This makes it easier than doing http requests (first to fetch api to get default branch zip url, second, to download file) and then to unzip it. When git clone will do all of this in one call.

**Review by AnonymousWalker — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Fetcher/198#-:-NyLcQqr92cP7_BaVbUM:bnfp4nl)* status: 0 of 26 files reviewed, 6 unresolved discussions (waiting on @mXaln)

**Pull request merged**
