### PR TITLE
Apply Dependency Injection Framework

### PR DESCRIPTION
**Pull request by AnonymousWalker**
This replaces DependencyResolver singleton object accross the web layer

---
This change is [Reviewable](https://reviewable.io/reviews/bible-translation-tools/fetcher/131)

### CODE REVIEW

**Review by jsarabia — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/fetcher/131)* status: 0 of 12 files reviewed, 4 unresolved discussions (waiting on @AnonymousWalker)

___
*[fetcher-web/build.gradle, line 6 at r1](https://reviewable.io/reviews/bible-translation-tools/fetcher/131#-MXsPHz281oBPrfId5oz:-MXsPHz281oBPrfId5p-:b-i8p1zb) ([raw file](https://github.com/bible-translation-tools/fetcher/blob/bdc16f204b00f83d8dbda06223e150be2f55e432/fetcher-web/build.gradle#L6)):*
> ```Gradle
>     repositories {
>         mavenCentral()
>         jcenter()
> ```

it would be preferable to not introduce jcenter as a dependency; it is being taken offline next year.
___
*[fetcher-web/build.gradle, line 58 at r1](https://reviewable.io/reviews/bible-translation-tools/fetcher/131#-MXsPUoD3cFFQPF3BGUL:-MXsPUoD3cFFQPF3BGUM:b1mgmd5) ([raw file](https://github.com/bible-translation-tools/fetcher/blob/bdc16f204b00f83d8dbda06223e150be2f55e432/fetcher-web/build.gradle#L58)):*
> ```Gradle
>     implementation "com.squareup.retrofit2:retrofit:$retrofit_ver"
>     implementation "me.xdrop:fuzzywuzzy:$fuzzy_wuzzy_ver"
>     implementation "org.koin:koin-ktor:$koin_ver"
> ```

io.insert-koin 
as per:
https://github.com/InsertKoinIO/koin#maven-central
___
*[fetcher-web/src/main/kotlin/org/bibletranslationtools/fetcher/web/AppModule.kt, line 81 at r1](https://reviewable.io/reviews/bible-translation-tools/fetcher/131#-MXsPwVu9gXSV6Ti13o7:-MXsPwVu9gXSV6Ti13o8:btqp9bg) ([raw file](https://github.com/bible-translation-tools/fetcher/blob/bdc16f204b00f83d8dbda06223e150be2f55e432/fetcher-web/src/main/kotlin/org/bibletranslationtools/fetcher/web/AppModule.kt#L81)):*
> ```Kotlin
>         while (true) {
>             Thread.sleep(CACHE_REFRESH_RATE_PER_HOUR * hours)
>             get(ContentCacheAccessor::class.java).update()
> ```

seems like we could do the get outside of the loop and save it to a variable
___
*[fetcher-web/src/main/kotlin/org/bibletranslationtools/fetcher/web/controllers/BookController.kt, line 60 at r1](https://reviewable.io/reviews/bible-translation-tools/fetcher/131#-MXsQ2hy9LiW8YwEwk2m:-MXsQ2hy9LiW8YwEwk2n:b-7ejzzw) ([raw file](https://github.com/bible-translation-tools/fetcher/blob/bdc16f204b00f83d8dbda06223e150be2f55e432/fetcher-web/src/main/kotlin/org/bibletranslationtools/fetcher/web/controllers/BookController.kt#L60)):*
> ```Kotlin
>         )
>     }
>     val language = get(LanguageRepository::class.java).getLanguage(params.languageCode)!!
> ```

why do all these things need ::class.java?
can you do get<LanguageRepository>()?

**Review by AnonymousWalker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/fetcher/131)* status: 0 of 12 files reviewed, 4 unresolved discussions (waiting on @AnonymousWalker and @jsarabia)

___
*[fetcher-web/src/main/kotlin/org/bibletranslationtools/fetcher/web/controllers/BookController.kt, line 60 at r1](https://reviewable.io/reviews/bible-translation-tools/fetcher/131#-MXsQ2hy9LiW8YwEwk2m:-MY2YAMp91_M2_Ak-JpG:bg6ht8) ([raw file](https://github.com/bible-translation-tools/fetcher/blob/bdc16f204b00f83d8dbda06223e150be2f55e432/fetcher-web/src/main/kotlin/org/bibletranslationtools/fetcher/web/controllers/BookController.kt#L60)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

why do all these things need ::class.java?
can you do get<LanguageRepository>()?

</blockquote></details>

get<T>() is extension method for Route, Routing, ktor Aplication

**Comment by AnonymousWalker** [comment]
___
*[fetcher-web/src/main/kotlin/org/bibletranslationtools/fetcher/web/controllers/BookController.kt, line 60 at r1](https://reviewable.io/reviews/bible-translation-tools/fetcher/131#-MXsQ2hy9LiW8YwEwk2m:-MY58F3d-QNWGJ339RG_:bmb2p5s) ([raw file](https://github.com/bible-translation-tools/fetcher/blob/bdc16f204b00f83d8dbda06223e150be2f55e432/fetcher-web/src/main/kotlin/org/bibletranslationtools/fetcher/web/controllers/BookController.kt#L60)):*
<details><summary><i>Previously, AnonymousWalker (Tony) wrote…</i></summary><blockquote>

get<T>() is extension method for Route, Routing, ktor Aplication
</blockquote></details>

since the function is not in the pipeline, I have to use the other one for common code. I looked into the get() methods in here and also the extension ones, I found that they actually doing similar thing: retrieve the dependency from GlobalContext().get() which gives a Koin instance, then .get() for the specific instance

https://github.com/InsertKoinIO/koin/blob/master/core/koin-core/src/jvmMain/kotlin/org/koin/java/KoinJavaComponent.kt

**Review by jsarabia — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/fetcher/131#-:-MY64i9p0uAa4b05uSDp:bnfp4nl)* status: 0 of 20 files reviewed, 1 unresolved discussion (waiting on @AnonymousWalker)

**Pull request merged**
