### PR TITLE
Temp Directory RC Cleanup

### PR DESCRIPTION
**Pull request by 16dprice**
This pull request will create the process that will periodically delete RC temp files that are beyond a certain age (2 weeks old). This PR depends on some env vars set in PR #77.

---
This change is [Reviewable](https://reviewable.io/reviews/bible-translation-tools/fetcher/78)

### CODE REVIEW

**Review by mXaln — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/fetcher/78)* status: all files reviewed, 1 unresolved discussion (waiting on @16dprice, @AnonymousWalker, @danparisd, and @jsarabia)

___
*[fetcher-pipeline/directorycleaner.py, line 57 at r2](https://reviewable.io/reviews/bible-translation-tools/fetcher/78#-MMRkXsUCT6of5Bx9tpd:-MMRkXsUCT6of5Bx9tpe:bhfc26g) ([raw file](https://github.com/bible-translation-tools/fetcher/blob/73f35a73d9548b2ed7399f050fa2ce99ef8a8bf3/fetcher-pipeline/directorycleaner.py#L57)):*
> ```Python
> 
> def main():
> ```

I would recommend add the logger in the script so we know what happened while script is running
```
logging.basicConfig(format='%(asctime)s - %(levelname)s: %(message)s', level=logging.DEBUG)
```

and then `logger.debug(<message>)` whenever something informative happens

**Review by 16dprice — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/fetcher/78)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @AnonymousWalker, @danparisd, @jsarabia, and @mXaln)

___
*[fetcher-pipeline/directorycleaner.py, line 57 at r2](https://reviewable.io/reviews/bible-translation-tools/fetcher/78#-MMRkXsUCT6of5Bx9tpd:-MMVf01l1p96G7Mul978:b-896fix) ([raw file](https://github.com/bible-translation-tools/fetcher/blob/73f35a73d9548b2ed7399f050fa2ce99ef8a8bf3/fetcher-pipeline/directorycleaner.py#L57)):*
<details><summary><i>Previously, mXaln (Maxim) wrote…</i></summary><blockquote>

I would recommend add the logger in the script so we know what happened while script is running
```
logging.basicConfig(format='%(asctime)s - %(levelname)s: %(message)s', level=logging.DEBUG)
```

and then `logger.debug(<message>)` whenever something informative happens
</blockquote></details>

Done.

**Review by mXaln — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/fetcher/78)* status: all files reviewed, 2 unresolved discussions (waiting on @16dprice, @AnonymousWalker, @danparisd, @jsarabia, and @mXaln)

___
*[fetcher-pipeline/directorycleaner.py, line 61 at r3](https://reviewable.io/reviews/bible-translation-tools/fetcher/78#-MMVgMhQ459B-7H7gEG_:-MMVgMhQ459B-7H7gEGa:b-2bl5ie) ([raw file](https://github.com/bible-translation-tools/fetcher/blob/ae5eff263a735c58f94044a6436b39fac281f3dd/fetcher-pipeline/directorycleaner.py#L61)):*
> ```Python
>     args, unknown = get_arguments()
> 
>     if args.trace:
> ```

You need to specify `trace` argument in `get_arguments` function
```
parser.add_argument("-t", "--trace", action="store_true", help="Enable tracing output")
```

**Review by jsarabia — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/fetcher/78)* status: all files reviewed, 3 unresolved discussions (waiting on @16dprice, @AnonymousWalker, @danparisd, and @mXaln)

___
*[fetcher-pipeline/entrypoint.sh, line 6 at r3](https://reviewable.io/reviews/bible-translation-tools/fetcher/78#-MMVhO9_AX3zH1R3g1VQ:-MMVhO9aA2JvhmN8JC0u:b1tvw94) ([raw file](https://github.com/bible-translation-tools/fetcher/blob/ae5eff263a735c58f94044a6436b39fac281f3dd/fetcher-pipeline/entrypoint.sh#L6)):*
> ```Shell
> 
> pm2 start "python3.8 app.py -i /content -t -v -hr 0 -mn 0" --name fetcher-pipeline
> pm2 start "python3.8 directorycleaner.py -hr 0 -mn 0" --name directory-cleaner
> ```

any particular reason we are specifying python3.8 and not python3?

**Review by 16dprice — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/fetcher/78)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @16dprice, @AnonymousWalker, @danparisd, and @mXaln)

___
*[fetcher-pipeline/directorycleaner.py, line 61 at r3](https://reviewable.io/reviews/bible-translation-tools/fetcher/78#-MMVgMhQ459B-7H7gEG_:-MMViANC2NutDoMwr1J3:b-896fix) ([raw file](https://github.com/bible-translation-tools/fetcher/blob/ae5eff263a735c58f94044a6436b39fac281f3dd/fetcher-pipeline/directorycleaner.py#L61)):*
<details><summary><i>Previously, mXaln (Maxim) wrote…</i></summary><blockquote>

You need to specify `trace` argument in `get_arguments` function
```
parser.add_argument("-t", "--trace", action="store_true", help="Enable tracing output")
```
</blockquote></details>

Done.

**Review by mXaln — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/fetcher/78)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @AnonymousWalker, @danparisd, @jsarabia, and @mXaln)

___
*[fetcher-pipeline/entrypoint.sh, line 6 at r3](https://reviewable.io/reviews/bible-translation-tools/fetcher/78#-MMVhO9_AX3zH1R3g1VQ:-MMViFSF1ityCrxvGTYy:b-8hkz2d) ([raw file](https://github.com/bible-translation-tools/fetcher/blob/ae5eff263a735c58f94044a6436b39fac281f3dd/fetcher-pipeline/entrypoint.sh#L6)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

any particular reason we are specifying python3.8 and not python3?
</blockquote></details>

@jsarabia I used python 3.8 because it's the minimal version to run fetcher-pipeline script. Not sure if other versions are installed in this container to run other scripts.

**Review by mXaln — COMMENTED** [review]
> Reviewed 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/fetcher/78)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @AnonymousWalker, @danparisd, @jsarabia, and @mXaln)

**Review by danparisd — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/fetcher/78)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @16dprice, @AnonymousWalker, @jsarabia, and @mXaln)

___
*[fetcher-pipeline/entrypoint.sh, line 6 at r4](https://reviewable.io/reviews/bible-translation-tools/fetcher/78#-MMVk7T70os0246duT_R:-MMVk7T70os0246duT_S:b-l5c9q6) ([raw file](https://github.com/bible-translation-tools/fetcher/blob/1564a3fa441843b98863217bd2b86cda1ab15943/fetcher-pipeline/entrypoint.sh#L6)):*
> ```Shell
> 
> pm2 start "python3.8 app.py -i /content -t -v -hr 0 -mn 0" --name fetcher-pipeline
> pm2 start "python3.8 directorycleaner.py -t -hr 0 -mn 0" --name directory-cleaner
> ```

Should we be running these two scripts at the same time? I think they don't operate on the same data, but might be good to run them at different times.

Now that I think about it, can we use env vars for the time for both scripts in case we need to change for prod after it starts being used?

**Review by 16dprice — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/fetcher/78)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @AnonymousWalker, @danparisd, @jsarabia, and @mXaln)

___
*[fetcher-pipeline/entrypoint.sh, line 6 at r4](https://reviewable.io/reviews/bible-translation-tools/fetcher/78#-MMVk7T70os0246duT_R:-MMVlV279aBk0K8QIxNC:bvhtcox) ([raw file](https://github.com/bible-translation-tools/fetcher/blob/1564a3fa441843b98863217bd2b86cda1ab15943/fetcher-pipeline/entrypoint.sh#L6)):*
<details><summary><i>Previously, danparisd wrote…</i></summary><blockquote>

Should we be running these two scripts at the same time? I think they don't operate on the same data, but might be good to run them at different times.

Now that I think about it, can we use env vars for the time for both scripts in case we need to change for prod after it starts being used?
</blockquote></details>

Is this relevant to help answer those questions?

https://futurestud.io/tutorials/pm2-start-multiple-apps-with-a-single-process-file-json-js-yaml

It seems like having a pm2-apps.json file could make operating multiple scripts at once easier to understand and to add onto later. It does feel like we're just pasting stuff onto something that's already working

**Comment by AnonymousWalker** [comment]
___
*[fetcher-pipeline/directorycleaner.py, line 35 at r4](https://reviewable.io/reviews/bible-translation-tools/fetcher/78#-MMVnSe14zzbIUhprZ0K:-MMVnSe28NEuDtKiwpyp:b-txjsy2) ([raw file](https://github.com/bible-translation-tools/fetcher/blob/1564a3fa441843b98863217bd2b86cda1ab15943/fetcher-pipeline/directorycleaner.py#L35)):*
> ```Python
> 
>     def delete_temp_rc_content(self):
>         file_paths = glob.glob(self.content_dir + "/*.zip")
> ```

So now we don't put these zip files at root of the current directory but rather contain them in a sub folder (named by a random UUID string). So we may want to delete these temp folders that are older than 2 weeks.

**Review by mXaln — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/fetcher/78)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @danparisd, @jsarabia, and @mXaln)

___
*[fetcher-pipeline/entrypoint.sh, line 6 at r4](https://reviewable.io/reviews/bible-translation-tools/fetcher/78#-MMVk7T70os0246duT_R:-MMVnPZ74EpwgolKgt4a:bv92efn) ([raw file](https://github.com/bible-translation-tools/fetcher/blob/1564a3fa441843b98863217bd2b86cda1ab15943/fetcher-pipeline/entrypoint.sh#L6)):*
<details><summary><i>Previously, 16dprice wrote…</i></summary><blockquote>

Is this relevant to help answer those questions?

https://futurestud.io/tutorials/pm2-start-multiple-apps-with-a-single-process-file-json-js-yaml

It seems like having a pm2-apps.json file could make operating multiple scripts at once easier to understand and to add onto later. It does feel like we're just pasting stuff onto something that's already working
</blockquote></details>

@danparisd It looks like a good idea!

@16dprice  When I started making that script I didn't think there will be others, so I decided not to use json config file. But now it sounds reasonable to use it. It's like docker-compose.yml fro pm2

**Review by AnonymousWalker — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/fetcher/78)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @16dprice, @danparisd, @jsarabia, and @mXaln)

**Review by 16dprice — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/fetcher/78)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @AnonymousWalker, @danparisd, @jsarabia, and @mXaln)

___
*[fetcher-pipeline/directorycleaner.py, line 35 at r4](https://reviewable.io/reviews/bible-translation-tools/fetcher/78#-MMVnSe14zzbIUhprZ0K:-MMVoSCA3LcvTkHq1fC4:b-896fix) ([raw file](https://github.com/bible-translation-tools/fetcher/blob/1564a3fa441843b98863217bd2b86cda1ab15943/fetcher-pipeline/directorycleaner.py#L35)):*
<details><summary><i>Previously, AnonymousWalker (Tony) wrote…</i></summary><blockquote>

So now we don't put these zip files at root of the current directory but rather contain them in a sub folder (named by a random UUID string). So we may want to delete these temp folders that are older than 2 weeks.
</blockquote></details>

Done.
___
*[fetcher-pipeline/entrypoint.sh, line 6 at r4](https://reviewable.io/reviews/bible-translation-tools/fetcher/78#-MMVk7T70os0246duT_R:-MMVoPkDBD19Y26RUH4p:behytjf) ([raw file](https://github.com/bible-translation-tools/fetcher/blob/1564a3fa441843b98863217bd2b86cda1ab15943/fetcher-pipeline/entrypoint.sh#L6)):*
<details><summary><i>Previously, mXaln (Maxim) wrote…</i></summary><blockquote>

@danparisd It looks like a good idea!

@16dprice  When I started making that script I didn't think there will be others, so I decided not to use json config file. But now it sounds reasonable to use it. It's like docker-compose.yml fro pm2
</blockquote></details>

Yep, I agree with that.

**Review by mXaln — APPROVED** [review]
> Reviewed 1 of 1 files at r5, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/fetcher/78)* status: all files reviewed, 2 unresolved discussions (waiting on @danparisd and @jsarabia)

**Review by danparisd — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/fetcher/78)* status: all files reviewed, 2 unresolved discussions (waiting on @16dprice, @jsarabia, and @mXaln)

___
*[fetcher-pipeline/entrypoint.sh, line 6 at r4](https://reviewable.io/reviews/bible-translation-tools/fetcher/78#-MMVk7T70os0246duT_R:-MMWOmHB7DmutvMM0jHb:b-wyq2mo) ([raw file](https://github.com/bible-translation-tools/fetcher/blob/1564a3fa441843b98863217bd2b86cda1ab15943/fetcher-pipeline/entrypoint.sh#L6)):*
<details><summary><i>Previously, 16dprice wrote…</i></summary><blockquote>

Yep, I agree with that.
</blockquote></details>

@16dprice @mxaln Do we want to make that change now, or do it later?

**Review by mXaln — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/fetcher/78)* status: all files reviewed, 2 unresolved discussions (waiting on @danparisd and @jsarabia)

___
*[fetcher-pipeline/entrypoint.sh, line 6 at r4](https://reviewable.io/reviews/bible-translation-tools/fetcher/78#-MMVk7T70os0246duT_R:-MMWrRBY5AIJBKqFL4r1:b-a6m45) ([raw file](https://github.com/bible-translation-tools/fetcher/blob/1564a3fa441843b98863217bd2b86cda1ab15943/fetcher-pipeline/entrypoint.sh#L6)):*
<details><summary><i>Previously, danparisd wrote…</i></summary><blockquote>

@16dprice @mxaln Do we want to make that change now, or do it later?
</blockquote></details>

@16dprice Could you set different env vars for your script, so we could specify different time for the scripts, if we want to?
```
DIRS_CLEANUP_HOUR=0
DIRS_CLEANUP_MINUTE=0
```

**Comment by AnonymousWalker** [comment]
___
*[fetcher-pipeline/entrypoint.sh, line 6 at r4](https://reviewable.io/reviews/bible-translation-tools/fetcher/78#-MMVk7T70os0246duT_R:-MMWuVq620d_31AESpcA:bb6un1j) ([raw file](https://github.com/bible-translation-tools/fetcher/blob/1564a3fa441843b98863217bd2b86cda1ab15943/fetcher-pipeline/entrypoint.sh#L6)):*
<details><summary><i>Previously, mXaln (Maxim) wrote…</i></summary><blockquote>

@16dprice Could you set different env vars for your script, so we could specify different time for the scripts, if we want to?
```
DIRS_CLEANUP_HOUR=0
DIRS_CLEANUP_MINUTE=0
```
</blockquote></details>

Done

**Review by mXaln — APPROVED** [review]
> Reviewed 1 of 1 files at r7, 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/fetcher/78)* status: all files reviewed, 2 unresolved discussions (waiting on @danparisd and @jsarabia)

**Comment by AnonymousWalker** [comment]
___
*[fetcher-pipeline/entrypoint.sh, line 6 at r4](https://reviewable.io/reviews/bible-translation-tools/fetcher/78#-MMVk7T70os0246duT_R:-MMX4umK0ahYCCO0rp7C:b-fqpucs) ([raw file](https://github.com/bible-translation-tools/fetcher/blob/1564a3fa441843b98863217bd2b86cda1ab15943/fetcher-pipeline/entrypoint.sh#L6)):*
<details><summary><i>Previously, AnonymousWalker (Tony) wrote…</i></summary><blockquote>

Done
</blockquote></details>

I think we can apply that change later in the subsequent PRs then (?)

**Review by danparisd — APPROVED** [review]
> Reviewed 1 of 1 files at r5, 2 of 2 files at r9.
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/fetcher/78)* status: all files reviewed, 2 unresolved discussions (waiting on @danparisd and @jsarabia)

**Review by danparisd — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/fetcher/78)* status: all files reviewed, 1 unresolved discussion (waiting on @jsarabia)

___
*[fetcher-pipeline/entrypoint.sh, line 6 at r4](https://reviewable.io/reviews/bible-translation-tools/fetcher/78#-MMVk7T70os0246duT_R:-MMX7_2R9XFNgx2mZemN:b32wtd) ([raw file](https://github.com/bible-translation-tools/fetcher/blob/1564a3fa441843b98863217bd2b86cda1ab15943/fetcher-pipeline/entrypoint.sh#L6)):*
<details><summary><i>Previously, AnonymousWalker (Tony) wrote…</i></summary><blockquote>

I think we can apply that change later in the subsequent PRs then (?)
</blockquote></details>

ok

**Pull request merged**
