### PR TITLE
CDN Base Url for Orature (RC) Files

### PR DESCRIPTION
**Pull request by AnonymousWalker**
Supports download rc files using the CDN URLs of file server

This change is [Reviewable](https://reviewable.io/reviews/bible-translation-tools/fetcher/116)

### CODE REVIEW

**Review by jsarabia — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/fetcher/116)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @AnonymousWalker and @danparisd)

___
*[fetcher-web/src/main/kotlin/org/bibletranslationtools/fetcher/usecase/RequestResourceContainer.kt, line 67 at r1](https://reviewable.io/reviews/bible-translation-tools/fetcher/116#-MUyeWDL0dRJFHVH_63Z:-MUyeWDL0dRJFHVH_63_:bb3iucq) ([raw file](https://github.com/bible-translation-tools/fetcher/blob/9a461e3abf1ffafd736d5c37b8cb30b460556d4a/fetcher-web/src/main/kotlin/org/bibletranslationtools/fetcher/usecase/RequestResourceContainer.kt#L67)):*
> ```Kotlin
>     }
> 
>     private fun formatDownloadUrl(file: File): String {
> ```

This looks like it could be a general utils function, not associated with any particular class, usable elsewhere in the future, rather than something specific to just resource container requests. What do you think?

**Review by jsarabia — DISMISSED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/fetcher/116#-:-MUyfDcSBITnuohkd9rf:bnfp4nl)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @danparisd)

**Comment by AnonymousWalker** [comment]
___
*[fetcher-web/src/main/kotlin/org/bibletranslationtools/fetcher/usecase/RequestResourceContainer.kt, line 67 at r1](https://reviewable.io/reviews/bible-translation-tools/fetcher/116#-MUyeWDL0dRJFHVH_63Z:-MUyetEiDsPBLYCeWUI1:b9mnvv) ([raw file](https://github.com/bible-translation-tools/fetcher/blob/9a461e3abf1ffafd736d5c37b8cb30b460556d4a/fetcher-web/src/main/kotlin/org/bibletranslationtools/fetcher/usecase/RequestResourceContainer.kt#L67)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

This looks like it could be a general utils function, not associated with any particular class, usable elsewhere in the future, rather than something specific to just resource container requests. What do you think?
</blockquote></details>

if so then it may need to take in an environment variable as parameter, since the other use cases also do the same thing with different env var. How do you think?

**Review by jsarabia — DISMISSED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/fetcher/116#-:-MUykD0FEYADEu87-PKk:bnfp4nl)* status: 0 of 6 files reviewed, all discussions resolved (waiting on @danparisd)

**Review by danparisd — APPROVED** [review]

**Pull request merged**
