### PR TITLE
Add support for heart languages

### PR DESCRIPTION
**Pull request by mXaln**
This change is [Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Fetcher/195)

### CODE REVIEW

**Review by AnonymousWalker — CHANGES_REQUESTED** [review]
if I remember correctly, the purpose of using the cache was to:
1. improve performance for page-load (GLs only)
2. avoid giving false positive - when the user click on something and then nothing is available

Maybe this could satisfy the first purpose which does not affect performance significantly. We need to verify this on dev after merging

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Fetcher/195#-:-Nxxd3M39K4b0WIo2G7X:b-igmiy8)* status: 0 of 19 files reviewed, 3 unresolved discussions (waiting on @mXaln)

___
*[`fetcher-web/src/main/kotlin/org/bibletranslationtools/fetcher/di/DIModule.kt` line 5 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Fetcher/195#-NxxYST60W6TFFNIUofT:-NxxYST60W6TFFNIUofU:b-rzzyam) ([raw file](https://github.com/Bible-Translation-Tools/Fetcher/blob/814708566df4b7e643dab0065aa110604ceff1ec/fetcher-web/src/main/kotlin/org/bibletranslationtools/fetcher/di/DIModule.kt#L5)):*
> ```Kotlin
> import org.bibletranslationtools.fetcher.config.DevEnvironmentConfig
> import org.bibletranslationtools.fetcher.config.EnvironmentConfig
> import org.bibletranslationtools.fetcher.impl.repository.*
> ```

please keep the import style consistent with how it was, this is easy to miss.
___
*[`fetcher-web/src/main/kotlin/org/bibletranslationtools/fetcher/usecase/FetchProductViewData.kt` line 25 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Fetcher/195#-NxxatWE3VMOjCs3yCm1:-NxxatWE3VMOjCs3yCm2:b-xz7xfe) ([raw file](https://github.com/Bible-Translation-Tools/Fetcher/blob/814708566df4b7e643dab0065aa110604ceff1ec/fetcher-web/src/main/kotlin/org/bibletranslationtools/fetcher/usecase/FetchProductViewData.kt#L25)):*
> ```Kotlin
>                 } else {
>                     listOf("mp3", "wav")
>                 }
> ```

Originally, we were using enums to avoid hard-coded strings like these. Could we keep that practice?
___
*[`fetcher-web/src/main/kotlin/org/bibletranslationtools/fetcher/web/controllers/BookController.kt` line 81 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Fetcher/195#-NxxaPt_33DfJ9-CFy4o:-NxxaPt_33DfJ9-CFy4p:btn8kyz) ([raw file](https://github.com/Bible-Translation-Tools/Fetcher/blob/814708566df4b7e643dab0065aa110604ceff1ec/fetcher-web/src/main/kotlin/org/bibletranslationtools/fetcher/web/controllers/BookController.kt#L81)):*
> ```Kotlin
>             "fileTypesNavTitle" to product.titleKey,
>             "fileTypesNavUrl" to "/$GL_ROUTE/${params.languageCode}",
>             "booksNavUrl" to "javascript:void(0)"
> ```

this feels wrong to use here

**Review by mXaln — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Fetcher/195)* status: 0 of 22 files reviewed, 3 unresolved discussions (waiting on @AnonymousWalker)

___
*[`fetcher-web/src/main/kotlin/org/bibletranslationtools/fetcher/di/DIModule.kt` line 5 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Fetcher/195#-NxxYST60W6TFFNIUofT:-Ny0JvhI4W_lkQkfaJ7k:b-nrnbgz) ([raw file](https://github.com/Bible-Translation-Tools/Fetcher/blob/814708566df4b7e643dab0065aa110604ceff1ec/fetcher-web/src/main/kotlin/org/bibletranslationtools/fetcher/di/DIModule.kt#L5)):*
<details><summary><i>Previously, AnonymousWalker (Tony) wrote…</i></summary><blockquote>

please keep the import style consistent with how it was, this is easy to miss.
</blockquote></details>

yeah, my IDE does that. Changed manually.
___
*[`fetcher-web/src/main/kotlin/org/bibletranslationtools/fetcher/usecase/FetchProductViewData.kt` line 25 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Fetcher/195#-NxxatWE3VMOjCs3yCm1:-Ny0K1FEDI-uL0yaM3dl:b-f3mweq) ([raw file](https://github.com/Bible-Translation-Tools/Fetcher/blob/814708566df4b7e643dab0065aa110604ceff1ec/fetcher-web/src/main/kotlin/org/bibletranslationtools/fetcher/usecase/FetchProductViewData.kt#L25)):*
<details><summary><i>Previously, AnonymousWalker (Tony) wrote…</i></summary><blockquote>

Originally, we were using enums to avoid hard-coded strings like these. Could we keep that practice?
</blockquote></details>

I was following the practice that was already in the code, like in the `FetchBookViewData`. Changed wherever I found it.
___
*[`fetcher-web/src/main/kotlin/org/bibletranslationtools/fetcher/web/controllers/BookController.kt` line 81 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Fetcher/195#-NxxaPt_33DfJ9-CFy4o:-Ny0MuZw5goTFM1WRDzI:bwqsy3x) ([raw file](https://github.com/Bible-Translation-Tools/Fetcher/blob/814708566df4b7e643dab0065aa110604ceff1ec/fetcher-web/src/main/kotlin/org/bibletranslationtools/fetcher/web/controllers/BookController.kt#L81)):*
<details><summary><i>Previously, AnonymousWalker (Tony) wrote…</i></summary><blockquote>

this feels wrong to use here
</blockquote></details>

Well it's just another type of url. Yeah, it looks like js code, but that's necessary to have it here. Could you suggest something different?

**Review by AnonymousWalker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Fetcher/195)* status: 0 of 22 files reviewed, all discussions resolved

___
*[`fetcher-web/src/main/kotlin/org/bibletranslationtools/fetcher/web/controllers/BookController.kt` line 81 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Fetcher/195#-NxxaPt_33DfJ9-CFy4o:-Ny10OS165ITRGLP7B5N:b-gyximv) ([raw file](https://github.com/Bible-Translation-Tools/Fetcher/blob/814708566df4b7e643dab0065aa110604ceff1ec/fetcher-web/src/main/kotlin/org/bibletranslationtools/fetcher/web/controllers/BookController.kt#L81)):*
<details><summary><i>Previously, mXaln (Maxim) wrote…</i></summary><blockquote>

Well it's just another type of url. Yeah, it looks like js code, but that's necessary to have it here. Could you suggest something different?
</blockquote></details>

Yes, https://github.com/Bible-Translation-Tools/Fetcher/pull/196

**Review by mXaln — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Fetcher/195)* status: 0 of 22 files reviewed, all discussions resolved (waiting on @AnonymousWalker)

___
*[`fetcher-web/src/main/kotlin/org/bibletranslationtools/fetcher/web/controllers/BookController.kt` line 81 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Fetcher/195#-NxxaPt_33DfJ9-CFy4o:-Ny16qrA9rSZvwVNrIIH:b-upz283) ([raw file](https://github.com/Bible-Translation-Tools/Fetcher/blob/814708566df4b7e643dab0065aa110604ceff1ec/fetcher-web/src/main/kotlin/org/bibletranslationtools/fetcher/web/controllers/BookController.kt#L81)):*
<details><summary><i>Previously, AnonymousWalker (Tony) wrote…</i></summary><blockquote>

Yes, https://github.com/Bible-Translation-Tools/Fetcher/pull/196
</blockquote></details>

ok, that works!

**Review by AnonymousWalker — APPROVED** [review]

**Pull request merged**
