### PR TITLE
Refactor orature download to reuse cached versions

### PR DESCRIPTION
**Pull request by mXaln**
This change is [Reviewable](https://reviewable.io/reviews/bible-translation-tools/fetcher/179)

### CODE REVIEW

**Review by AnonymousWalker — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/fetcher/179)* status: 0 of 8 files reviewed, 2 unresolved discussions (waiting on @AnonymousWalker and @mXaln)

___
*[`fetcher-web/src/main/resources/css/chapters.css` line 151 at r2](https://reviewable.io/reviews/bible-translation-tools/fetcher/179#-N2D2m1y1rQya0Fp3kGJ:-N2D2m1y1rQya0Fp3kGK:bkja1u) ([raw file](https://github.com/bible-translation-tools/fetcher/blob/40a3393e21b673508b6daeaa2a378a0432137c9c/fetcher-web/src/main/resources/css/chapters.css#L151)):*
> ```CSS
> }
> 
> .chapter-card-error.chapter-download__error {
> ```

`.chapter-card-error` looks like a duplicate of the existing `.chaptercard`

Because the existing `.chaptercard` selector has adaptive UI binding (for mobile devices), you should try to reuse it. 
An issue I see in tablet mode (browser debug) is the width of the error text.
___
*[`fetcher-web/src/main/resources/templates/fragments/chaptercard.html` line 22 at r2](https://reviewable.io/reviews/bible-translation-tools/fetcher/179#-N2D4DDVDYLoFbg10gMd:-N2D4DDVDYLoFbg10gMe:b-jxxyjp) ([raw file](https://github.com/bible-translation-tools/fetcher/blob/40a3393e21b673508b6daeaa2a378a0432137c9c/fetcher-web/src/main/resources/templates/fragments/chaptercard.html#L22)):*
> ```HTML
>                 <em class="material-icons chaptercard__icon" th:classappend="${url == null}? 'unavailable'">get_app</em>
>                 Spinner Icon
>                 <p class="chaptercard__download-text" name="download-text" th:text="#{download}">Download</p>
> ```

I believe there still be situations where the resource doesn't exist at the time the user requests (cache miss), which introduce a delay. Therefore, we used the term "Request" for the appropriate purpose. When it's ready, the button changes to "Download" and auto-click presumably.

**Comment by AnonymousWalker** [comment]
Thanks for refactoring the source code 👯

**Review by AnonymousWalker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/fetcher/179)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @AnonymousWalker and @mXaln)

___
*[`fetcher-web/src/main/resources/css/chapters.css` line 151 at r2](https://reviewable.io/reviews/bible-translation-tools/fetcher/179#-N2D2m1y1rQya0Fp3kGJ:-N2D6iQnC4SlO8GnPGXR:b2o0nok) ([raw file](https://github.com/bible-translation-tools/fetcher/blob/40a3393e21b673508b6daeaa2a378a0432137c9c/fetcher-web/src/main/resources/css/chapters.css#L151)):*
<details><summary><i>Previously, AnonymousWalker (Tony) wrote…</i></summary><blockquote>

`.chapter-card-error` looks like a duplicate of the existing `.chaptercard`

Because the existing `.chaptercard` selector has adaptive UI binding (for mobile devices), you should try to reuse it. 

Also, `color: black` is default, if there is a need to set it at container-level like this, it shows a warning sign that somewhere the styling isn't modular/specific which messes up the default
</blockquote></details>

actually, that's fine to set the color at block level

**Review by AnonymousWalker — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/fetcher/179)* status: 0 of 8 files reviewed, 2 unresolved discussions (waiting on @AnonymousWalker and @mXaln)

___
*[`fetcher-web/src/main/resources/css/chapters.css` line 151 at r2](https://reviewable.io/reviews/bible-translation-tools/fetcher/179#-N2D2m1y1rQya0Fp3kGJ:-N2D7Ebo6ZFj0cKKzrDN:b-ak2c7b) ([raw file](https://github.com/bible-translation-tools/fetcher/blob/40a3393e21b673508b6daeaa2a378a0432137c9c/fetcher-web/src/main/resources/css/chapters.css#L151)):*
<details><summary><i>Previously, AnonymousWalker (Tony) wrote…</i></summary><blockquote>

actually, that's fine to set the color at block level
</blockquote></details>

as `.chapter-card-error` doesn't have the adaptive sizing with `@media...` like `.chaptercard` does, it causes a bug in tablet mode when request returns error

**Review by AnonymousWalker — COMMENTED** [review]
> Reviewed 2 of 7 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/fetcher/179)* status: 3 of 8 files reviewed, all discussions resolved (waiting on @AnonymousWalker)

**Review by AnonymousWalker — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/fetcher/179)* status: 3 of 8 files reviewed, 1 unresolved discussion (waiting on @AnonymousWalker and @mXaln)

**Review by mXaln — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/fetcher/179)* status: 3 of 8 files reviewed, 1 unresolved discussion (waiting on @AnonymousWalker)

___
*[`fetcher-web/src/main/resources/css/chapters.css` line 151 at r2](https://reviewable.io/reviews/bible-translation-tools/fetcher/179#-N2D2m1y1rQya0Fp3kGJ:-N2H4FyP-QKKE0sDSmHQ:bbdirj4) ([raw file](https://github.com/bible-translation-tools/fetcher/blob/40a3393e21b673508b6daeaa2a378a0432137c9c/fetcher-web/src/main/resources/css/chapters.css#L151)):*
<details><summary><i>Previously, AnonymousWalker (Tony) wrote…</i></summary><blockquote>

as `.chapter-card-error` doesn't have the adaptive sizing with `@media...` like `.chaptercard` does, it causes a bug in tablet mode when request returns error



</blockquote></details>

I have to use `.chapter-card-error` and `.book-card-error` classes to differentiate two buttons and don't the mess styles for both of them. Also I didn't want to put the error component inside the `a` tag. So I fixed this for small screens by adding a couple more css rules.
___
*[`fetcher-web/src/main/resources/templates/fragments/chaptercard.html` line 22 at r2](https://reviewable.io/reviews/bible-translation-tools/fetcher/179#-N2D4DDVDYLoFbg10gMd:-N2GgLym1u6A1hoHMdgM:b-rh1vwb) ([raw file](https://github.com/bible-translation-tools/fetcher/blob/40a3393e21b673508b6daeaa2a378a0432137c9c/fetcher-web/src/main/resources/templates/fragments/chaptercard.html#L22)):*
<details><summary><i>Previously, AnonymousWalker (Tony) wrote…</i></summary><blockquote>

I believe there still be situations where the resource doesn't exist at the time the user requests (cache miss), which introduce a delay. Therefore, we used the term "Request" for the appropriate purpose. When it's ready, the button changes to "Download" and auto-click presumably.
</blockquote></details>

Thomas made this design. And I agree with him. 

From the user perspective it is just a button, which they click to download the file. They don't care whether it is requesting a new file or provides a cached version, 'cause they don't need to click it twice anymore.

**Review by AnonymousWalker — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/fetcher/179#-:-N2HT3tAC8s3bOT9BfAF:bnfp4nl)* status: 3 of 8 files reviewed, 1 unresolved discussion (waiting on @AnonymousWalker)

**Pull request merged**
