### PR TITLE
Added try catch block to processes to control their exceptions

### PR DESCRIPTION
**Pull request by mXaln**
This change is [Reviewable](https://reviewable.io/reviews/bible-translation-tools/fetcher/97)

### CODE REVIEW

**Review by jsarabia — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/fetcher/97)* status: 0 of 8 files reviewed, 6 unresolved discussions (waiting on @danparisd, @mXaln, and @rbnswartz)

___
*[fetcher-pipeline/book_worker.py, line 32 at r1](https://reviewable.io/reviews/bible-translation-tools/fetcher/97#-MTHKjRR1ZEPDwvRyOSe:-MTHKjRSAqixIMxmnthu:b-49wqvv) ([raw file](https://github.com/bible-translation-tools/fetcher/blob/71d99c21d6a01fde973ecf486dcfbf4b697c839a/fetcher-pipeline/book_worker.py#L32)):*
> ```Python
>         logging.debug("=================== Book worker started! =====================")
>         logging.debug(".................................................................")
>         logging.debug("=================================================================")
> ```

ascii art here, while human readable, will make reading through logs very difficult as usage scales. I understand this is a debug message, but maybe some of our debug logs should actually be a low level log like info. 

There are plenty of software tools for log analysis out there to filter things and make logs easier to manage and read through, but in order to make the most of them, we need to know how to template logs well to make them parse easily by a computer (while still being human readable)

I think @danparisd should advise a little on tooling and log analytics, but overall writing good logs and learning best practices is an important part of backend development and something we should work on.
___
*[fetcher-pipeline/chapter_worker.py, line 39 at r1](https://reviewable.io/reviews/bible-translation-tools/fetcher/97#-MTHK-bLDn4uOijX9jia:-MTHK-bM9aGFk879K7yP:bfc94py) ([raw file](https://github.com/bible-translation-tools/fetcher/blob/71d99c21d6a01fde973ecf486dcfbf4b697c839a/fetcher-pipeline/chapter_worker.py#L39)):*
> ```Python
>         try:
>             for src_file in self.__ftp_dir.rglob('*.wav'):
>                 try:
> ```

Looks like the code within this try should probably be a function
___
*[fetcher-pipeline/chapter_worker.py, line 52 at r1](https://reviewable.io/reviews/bible-translation-tools/fetcher/97#-MTHKA6a42Yue3LNnsaQ:-MTHKA6a42Yue3LNnsaR:bc41h8a) ([raw file](https://github.com/bible-translation-tools/fetcher/blob/71d99c21d6a01fde973ecf486dcfbf4b697c839a/fetcher-pipeline/chapter_worker.py#L52)):*
> ```Python
>                     book = parts[2]
>                     chapter = parts[3]
>                     grouping = parts[6]
> ```

Should parts be a dictionary so instead of looking up things by specific indexes, we use a key value?
___
*[fetcher-pipeline/chapter_worker.py, line 88 at r1](https://reviewable.io/reviews/bible-translation-tools/fetcher/97#-MTHKVai3G8L9enu5DcX:-MTHKVai3G8L9enu5DcY:b2x6i2) ([raw file](https://github.com/bible-translation-tools/fetcher/blob/71d99c21d6a01fde973ecf486dcfbf4b697c839a/fetcher-pipeline/chapter_worker.py#L88)):*
> ```Python
>                     # delete all the chapter related resources:
>                     # split verses, converted files, TR files and book files
>                     if cleaning:
> ```

could the code in this block form a cleanup function?
___
*[fetcher-pipeline/chapter_worker.py, line 122 at r1](https://reviewable.io/reviews/bible-translation-tools/fetcher/97#-MTHLvBk-tNkexfe4FEz:-MTHLvBk-tNkexfe4FF-:bedu160) ([raw file](https://github.com/bible-translation-tools/fetcher/blob/71d99c21d6a01fde973ecf486dcfbf4b697c839a/fetcher-pipeline/chapter_worker.py#L122)):*
> ```Python
>                     self.convert_verses_wav(verses_dir, remote_dir, 'low')
>                 except Exception as e:
>                     logging.warning(str(e))
> ```

it looks like the exception was always here, so I'm not sure  what the issue was previously? This will catch any exception, so the outer try should never catch anything, so the code in the finally should have always run?
___
*[fetcher-pipeline/tr_worker.py, line 91 at r1](https://reviewable.io/reviews/bible-translation-tools/fetcher/97#-MTHMLfwDbljo6RPd-pB:-MTHMLfwDbljo6RPd-pC:bnkj50c) ([raw file](https://github.com/bible-translation-tools/fetcher/blob/71d99c21d6a01fde973ecf486dcfbf4b697c839a/fetcher-pipeline/tr_worker.py#L91)):*
> ```Python
>                             self.__chapter_tr_files.remove(src_file)
> 
>             # Create chapter TRs
> ```

can't these be functions?

**Review by mXaln — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/fetcher/97)* status: 0 of 8 files reviewed, 6 unresolved discussions (waiting on @danparisd, @jsarabia, and @rbnswartz)

___
*[fetcher-pipeline/book_worker.py, line 32 at r1](https://reviewable.io/reviews/bible-translation-tools/fetcher/97#-MTHKjRR1ZEPDwvRyOSe:-MTJtSap81XfQl-nTGRY:b-896fix) ([raw file](https://github.com/bible-translation-tools/fetcher/blob/71d99c21d6a01fde973ecf486dcfbf4b697c839a/fetcher-pipeline/book_worker.py#L32)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

ascii art here, while human readable, will make reading through logs very difficult as usage scales. I understand this is a debug message, but maybe some of our debug logs should actually be a low level log like info. 

There are plenty of software tools for log analysis out there to filter things and make logs easier to manage and read through, but in order to make the most of them, we need to know how to template logs well to make them parse easily by a computer (while still being human readable)

I think @danparisd should advise a little on tooling and log analytics, but overall writing good logs and learning best practices is an important part of backend development and something we should work on.
</blockquote></details>

Done.
___
*[fetcher-pipeline/chapter_worker.py, line 39 at r1](https://reviewable.io/reviews/bible-translation-tools/fetcher/97#-MTHK-bLDn4uOijX9jia:-MTJwHR773it3tUlI0aa:b-896fix) ([raw file](https://github.com/bible-translation-tools/fetcher/blob/71d99c21d6a01fde973ecf486dcfbf4b697c839a/fetcher-pipeline/chapter_worker.py#L39)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

Looks like the code within this try should probably be a function
</blockquote></details>

Done.
___
*[fetcher-pipeline/chapter_worker.py, line 52 at r1](https://reviewable.io/reviews/bible-translation-tools/fetcher/97#-MTHKA6a42Yue3LNnsaQ:-MTJunsu4HiJDaV-a1TK:bdkgajo) ([raw file](https://github.com/bible-translation-tools/fetcher/blob/71d99c21d6a01fde973ecf486dcfbf4b697c839a/fetcher-pipeline/chapter_worker.py#L52)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

Should parts be a dictionary so instead of looking up things by specific indexes, we use a key value?
</blockquote></details>

pathlib.parts returns tupple, not dictionary. I'm not sure if I can get a dictinary, unless I create one. But for what reason?
___
*[fetcher-pipeline/chapter_worker.py, line 88 at r1](https://reviewable.io/reviews/bible-translation-tools/fetcher/97#-MTHKVai3G8L9enu5DcX:-MTJwJfT0Z_Y8rNetmdr:b-896fix) ([raw file](https://github.com/bible-translation-tools/fetcher/blob/71d99c21d6a01fde973ecf486dcfbf4b697c839a/fetcher-pipeline/chapter_worker.py#L88)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

could the code in this block form a cleanup function?
</blockquote></details>

Done.
___
*[fetcher-pipeline/chapter_worker.py, line 122 at r1](https://reviewable.io/reviews/bible-translation-tools/fetcher/97#-MTHLvBk-tNkexfe4FEz:-MTJwOEh6m-vB8ic_Hb5:b-u28jgt) ([raw file](https://github.com/bible-translation-tools/fetcher/blob/71d99c21d6a01fde973ecf486dcfbf4b697c839a/fetcher-pipeline/chapter_worker.py#L122)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

it looks like the exception was always here, so I'm not sure  what the issue was previously? This will catch any exception, so the outer try should never catch anything, so the code in the finally should have always run?
</blockquote></details>

previously, if a subprocess failed, the app exited (sys.exit(1)). Instead of doing that, now function throws an exception if a subprocess fails. But you are right two try/catch blocks are redundant here. Removed one of them.
___
*[fetcher-pipeline/tr_worker.py, line 91 at r1](https://reviewable.io/reviews/bible-translation-tools/fetcher/97#-MTHMLfwDbljo6RPd-pB:-MTK-0K32Gck_eZMTjBt:b-896fix) ([raw file](https://github.com/bible-translation-tools/fetcher/blob/71d99c21d6a01fde973ecf486dcfbf4b697c839a/fetcher-pipeline/tr_worker.py#L91)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

can't these be functions?
</blockquote></details>

Done.

**Review by danparisd — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/fetcher/97)* status: 0 of 8 files reviewed, 7 unresolved discussions (waiting on @jsarabia, @mXaln, and @rbnswartz)

___
*[fetcher-pipeline/book_worker.py, line 32 at r1](https://reviewable.io/reviews/bible-translation-tools/fetcher/97#-MTHKjRR1ZEPDwvRyOSe:-MTLRbOWDkybT4g_MWo1:b4rennr) ([raw file](https://github.com/bible-translation-tools/fetcher/blob/71d99c21d6a01fde973ecf486dcfbf4b697c839a/fetcher-pipeline/book_worker.py#L32)):*
<details><summary><i>Previously, mXaln (Maxim) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

We're going to be shipping the logs to an ELK stack via Docker, so as long as the logs go to stdout we should be good. Kibana is the searching/visualizing tool in that stack, and we can build searches for just about anything, so it can be as structured (template) or unstructured (human readable message) as y'all want.
___
*[fetcher-pipeline/Dockerfile, line 20 at r2](https://reviewable.io/reviews/bible-translation-tools/fetcher/97#-MTLTA3yEKWP4HcSXDz4:-MTLTA3yEKWP4HcSXDz5:b-fm2243) ([raw file](https://github.com/bible-translation-tools/fetcher/blob/61097cc860655b30aefd3bd64e6d734ab51a2f76/fetcher-pipeline/Dockerfile#L20)):*
> ```Dockerfile
> ENV PATH $JAVA_HOME/bin:$PATH
> 
> RUN wget -qO - https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
> ```

What's this for?

**Review by jsarabia — DISMISSED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/fetcher/97#-:-MTLl3cv--H5L5eTS3Oh:bnfp4nl)* status: 0 of 8 files reviewed, 2 unresolved discussions (waiting on @jsarabia, @mXaln, and @rbnswartz)

**Review by mXaln — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/fetcher/97)* status: 0 of 8 files reviewed, 2 unresolved discussions (waiting on @danparisd, @jsarabia, and @rbnswartz)

___
*[fetcher-pipeline/Dockerfile, line 20 at r2](https://reviewable.io/reviews/bible-translation-tools/fetcher/97#-MTLTA3yEKWP4HcSXDz4:-MTLlHIi36DDMVhKJEEF:b-bgk4vi) ([raw file](https://github.com/bible-translation-tools/fetcher/blob/61097cc860655b30aefd3bd64e6d734ab51a2f76/fetcher-pipeline/Dockerfile#L20)):*
<details><summary><i>Previously, danparisd wrote…</i></summary><blockquote>

What's this for?
</blockquote></details>

@danparisd , I faced this issue yesterday, while I was rebuilding fetcher-pipeline container. This issue is described here https://github.com/yarnpkg/yarn/issues/4453. It looks like yarn public key was outdated in debian repository. So the soultion is to manually download the public key.

**Review by danparisd — APPROVED** [review]
> Reviewed 3 of 8 files at r1, 4 of 4 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/fetcher/97)* status: all files reviewed, 2 unresolved discussions (waiting on @danparisd, @jsarabia, and @rbnswartz)

**Pull request merged**
